DROP EXTENSION IF EXISTS postgis_topology;
DROP EXTENSION IF EXISTS postgis;
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
-- Supression schemas
DROP SCHEMA INF CASCADE;
DROP SCHEMA PRF CASCADE;
DROP SCHEMA SIG CASCADE;
-- Schemas
CREATE SCHEMA INF AUTHORIZATION postgres;
COMMENT ON SCHEMA INF IS 'Référentiel';
CREATE SCHEMA PRF AUTHORIZATION postgres;
COMMENT ON SCHEMA PRF IS 'Gestion des utilisateurs';
CREATE SCHEMA SIG AUTHORIZATION postgres;
COMMENT ON SCHEMA SIG IS 'Système d''information géographique';

-- Tables
-- Table INF.INF_ACCIDENT -> Référentiel Accident
CREATE TABLE INF.INF_ACCIDENT
(
INF_ACCIDENT__ANNEE integer NOT NULL,
INF_ACCIDENT__ABS_DEB integer NOT NULL,
INF_ACCIDENT__ABS_FIN integer,
INF_ACCIDENT__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_ACCIDENT__MOIS integer NOT NULL,
INF_ACCIDENT__NB integer,
INF_ACCIDENT__NB_MOIS integer
);
COMMENT ON TABLE INF.INF_ACCIDENT IS 'Accident';
COMMENT ON COLUMN INF.INF_ACCIDENT.INF_ACCIDENT__ANNEE IS 'Année';
COMMENT ON COLUMN INF.INF_ACCIDENT.INF_ACCIDENT__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_ACCIDENT.INF_ACCIDENT__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_ACCIDENT.INF_ACCIDENT__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_ACCIDENT.INF_CHAUSSEE__ID IS 'Identifiant2';
COMMENT ON COLUMN INF.INF_ACCIDENT.INF_ACCIDENT__MOIS IS 'Mois';
COMMENT ON COLUMN INF.INF_ACCIDENT.INF_ACCIDENT__NB IS 'Nb accident';
COMMENT ON COLUMN INF.INF_ACCIDENT.INF_ACCIDENT__NB_MOIS IS 'Nb accident par mois';

-- Table INF.INF_AIRE_PARKING -> Référentiel Aire parking
CREATE TABLE INF.INF_AIRE_PARKING
(
INF_AIRE_PARKING__ID serial NOT NULL,
INF_AIRE__ID integer,
INF_CD_PLACE__ID integer,
INF_AIRE_PARKING__NB_PLACE integer
);
COMMENT ON TABLE INF.INF_AIRE_PARKING IS 'Aire parking';
COMMENT ON COLUMN INF.INF_AIRE_PARKING.INF_AIRE_PARKING__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_AIRE_PARKING.INF_AIRE__ID IS 'Identifiant aire';
COMMENT ON COLUMN INF.INF_AIRE_PARKING.INF_CD_PLACE__ID IS 'Identifiant type parking';
COMMENT ON COLUMN INF.INF_AIRE_PARKING.INF_AIRE_PARKING__NB_PLACE IS 'Nombre de place';

-- Table INF.INF_AIRE_PRESTATAIRE -> Référentiel Aire prestataire
CREATE TABLE INF.INF_AIRE_PRESTATAIRE
(
INF_AIRE_PRESTATAIRE__ID serial NOT NULL,
INF_AIRE__ID integer,
INF_PRESTATAIRE__ID integer
);
COMMENT ON TABLE INF.INF_AIRE_PRESTATAIRE IS 'Aire prestataire';
COMMENT ON COLUMN INF.INF_AIRE_PRESTATAIRE.INF_AIRE_PRESTATAIRE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_AIRE_PRESTATAIRE.INF_AIRE__ID IS 'Identifiant aire';
COMMENT ON COLUMN INF.INF_AIRE_PRESTATAIRE.INF_PRESTATAIRE__ID IS 'Identifiant prestataire';

-- Table INF.INF_AIRE_SERVICE -> Référentiel Aire service
CREATE TABLE INF.INF_AIRE_SERVICE
(
INF_AIRE_SERVICE__ID serial NOT NULL,
INF_AIRE__ID integer,
INF_CD_SERVICE__ID integer
);
COMMENT ON TABLE INF.INF_AIRE_SERVICE IS 'Aire service';
COMMENT ON COLUMN INF.INF_AIRE_SERVICE.INF_AIRE_SERVICE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_AIRE_SERVICE.INF_AIRE__ID IS 'Identifiant aire';
COMMENT ON COLUMN INF.INF_AIRE_SERVICE.INF_CD_SERVICE__ID IS 'Identifiant type service';

-- Table INF.INF_AIRE -> Référentiel Aires
CREATE TABLE INF.INF_AIRE
(
INF_AIRE__BILATERALE boolean,
INF_AIRE__OBSERV character varying(250),
INF_AIRE__DATE_MS date,
INF_AIRE__ABS_DEB integer NOT NULL,
INF_AIRE__DEMI_TOUR boolean,
INF_AIRE__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_AIRE__ID integer NOT NULL,
INF_AIRE__NUM_EXPLOIT character varying(15),
INF_AIRE__NOM character varying(60),
INF_AIRE__PASSERELLE boolean
);
COMMENT ON TABLE INF.INF_AIRE IS 'Aires';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__BILATERALE IS 'Bilatérale';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__OBSERV IS 'Commentaires';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__DATE_MS IS 'Date MS';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__DEMI_TOUR IS 'Demi tour';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_AIRE.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_AIRE.INF_CD_AIRE__ID IS 'Identifiant type aire';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__NUM_EXPLOIT IS 'N° Exploitation';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__NOM IS 'Nom d''usage';
COMMENT ON COLUMN INF.INF_AIRE.INF_AIRE__PASSERELLE IS 'Passerelle';

-- Table INF.INF_AMENAGEMENT -> Référentiel Aménagement
CREATE TABLE INF.INF_AMENAGEMENT
(
INF_AMENAGEMENT__INFO character varying(500),
INF_AMENAGEMENT__COUT integer,
INF_AMENAGEMENT__DATE_DEB date NOT NULL,
INF_AMENAGEMENT__DATE_FIN date,
INF_AMENAGEMENT__ABS_DEB integer NOT NULL,
INF_AMENAGEMENT__ABS_FIN integer,
INF_AMENAGEMENT__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_AMENAGEMENT__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_AMENAGEMENT IS 'Aménagement';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_AMENAGEMENT__INFO IS 'Commentaire';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_AMENAGEMENT__COUT IS 'Coût';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_AMENAGEMENT__DATE_DEB IS 'Date début';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_AMENAGEMENT__DATE_FIN IS 'Date fin';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_AMENAGEMENT__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_AMENAGEMENT__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_AMENAGEMENT__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_AMENAGEMENT.INF_CD_AMENAGEMENT__ID IS 'Identifiant code aménagement';

-- Table INF.INF_PR_OLD -> Référentiel Ancien repérage
CREATE TABLE INF.INF_PR_OLD
(
INF_PR_OLD__ABS_CUM integer NOT NULL,
INF_PR_OLD__INTER integer NOT NULL,
INF_PR_OLD__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_PR_OLD__NUM integer NOT NULL
);
COMMENT ON TABLE INF.INF_PR_OLD IS 'Ancien repérage';
COMMENT ON COLUMN INF.INF_PR_OLD.INF_PR_OLD__ABS_CUM IS 'Abscisse';
COMMENT ON COLUMN INF.INF_PR_OLD.INF_PR_OLD__INTER IS 'Distance inter PR';
COMMENT ON COLUMN INF.INF_PR_OLD.INF_PR_OLD__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_PR_OLD.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_PR_OLD.INF_PR_OLD__NUM IS 'N° de PR';

-- Table INF.INF_BIFURCATION -> Référentiel Bifurcation
CREATE TABLE INF.INF_BIFURCATION
(
INF_BIFURCATION__INFO character varying(500),
INF_BIFURCATION__DATE_MS date,
INF_BIFURCATION__ABS_DEB integer NOT NULL,
INF_BIFURCATION__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_BIFURCATION__ID integer NOT NULL,
INF_BIFURCATION__NUM_EXPLOIT character varying(50),
INF_BIFURCATION__NOM character varying(100)
);
COMMENT ON TABLE INF.INF_BIFURCATION IS 'Bifurcation';
COMMENT ON COLUMN INF.INF_BIFURCATION.INF_BIFURCATION__INFO IS 'Commentaire';
COMMENT ON COLUMN INF.INF_BIFURCATION.INF_BIFURCATION__DATE_MS IS 'Date MS';
COMMENT ON COLUMN INF.INF_BIFURCATION.INF_BIFURCATION__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_BIFURCATION.INF_BIFURCATION__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_BIFURCATION.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_BIFURCATION.INF_CD_BIFURCATION__ID IS 'Identifiant code bifurcation';
COMMENT ON COLUMN INF.INF_BIFURCATION.INF_BIFURCATION__NUM_EXPLOIT IS 'N° exploitation';
COMMENT ON COLUMN INF.INF_BIFURCATION.INF_BIFURCATION__NOM IS 'Nom';

-- Table INF.INF_BRETELLE -> Référentiel Bretelle
CREATE TABLE INF.INF_BRETELLE
(
INF_BRETELLE__ABS_DEB integer NOT NULL,
INF_BRETELLE__EXTREMITE character varying(100),
INF_BRETELLE__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_BRETELLE__LIBELLE character varying(200),
INF_BRETELLE__NUM character varying(50),
INF_BRETELLE__NUM_EXPLOIT character varying(50),
INF_BRETELLE__NOM character varying(100),
INF_BRETELLE__TYPE character varying(50)
);
COMMENT ON TABLE INF.INF_BRETELLE IS 'Bretelle';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_BRETELLE__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_BRETELLE__EXTREMITE IS 'Extrémité';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_BRETELLE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_BRETELLE__LIBELLE IS 'Libellé';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_BRETELLE__NUM IS 'N° bretelle';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_BRETELLE__NUM_EXPLOIT IS 'N° exploitation';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_BRETELLE__NOM IS 'Nom bretelle';
COMMENT ON COLUMN INF.INF_BRETELLE.INF_BRETELLE__TYPE IS 'Type';

-- Table INF.INF_CHAUSSEE -> Référentiel Chaussée
CREATE TABLE INF.INF_CHAUSSEE
(
INF_CHAUSSEE__ABOUT character varying(200),
INF_CHAUSSEE__CODE character varying(50) NOT NULL,
INF_CHAUSSEE__ABS_DEB integer NOT NULL,
INF_CHAUSSEE__ABS_FIN integer NOT NULL,
INF_CHAUSSEE__GEOM geometry,
INF_CHAUSSEE__ID serial NOT NULL,
INF_LIAISON__ID integer NOT NULL,
INF_CHAUSSEE__LIBELLE character varying(200),
INF_CHAUSSEE__TENANT character varying(200)
);
COMMENT ON TABLE INF.INF_CHAUSSEE IS 'Chaussée';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_CHAUSSEE__ABOUT IS 'Aboutissant';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_CHAUSSEE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_CHAUSSEE__ABS_DEB IS 'Debut';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_CHAUSSEE__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_CHAUSSEE__GEOM IS 'Géométrie';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_CHAUSSEE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_LIAISON__ID IS 'Identifiant liaison';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_CHAUSSEE__LIBELLE IS 'Libellé';
COMMENT ON COLUMN INF.INF_CHAUSSEE.INF_CHAUSSEE__TENANT IS 'Tenant';

-- Table INF.INF_CD_TRAFIC -> Référentiel Classe de trafic
CREATE TABLE INF.INF_CD_TRAFIC
(
INF_CD_TRAFIC__CODE character varying(50) NOT NULL,
INF_CD_TRAFIC__ID serial NOT NULL,
INF_CD_TRAFIC__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_TRAFIC IS 'Classe de trafic';
COMMENT ON COLUMN INF.INF_CD_TRAFIC.INF_CD_TRAFIC__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_TRAFIC.INF_CD_TRAFIC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_TRAFIC.INF_CD_TRAFIC__LIBELLE IS 'Libellé';

-- Table INF.INF_CLS -> Référentiel Classeurs
CREATE TABLE INF.INF_CLS
(
INF_CLS__ID serial NOT NULL,
INF_CLS__ROW_ID integer,
INF_CLS__TABLE_NAME character varying(50) NOT NULL
);
COMMENT ON TABLE INF.INF_CLS IS 'Classeurs';
COMMENT ON COLUMN INF.INF_CLS.INF_CLS__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CLS.INF_CLS__ROW_ID IS 'Identifiant ligne';
COMMENT ON COLUMN INF.INF_CLS.INF_CLS__TABLE_NAME IS 'Table';

-- Table INF.INF_CLIMAT -> Référentiel Climat
CREATE TABLE INF.INF_CLIMAT
(
INF_CLIMAT__INFO character varying(500),
INF_CLIMAT__ABS_DEB integer NOT NULL,
INF_CLIMAT__ABS_FIN integer NOT NULL,
INF_CLIMAT__ID serial NOT NULL,
INF_CD_CLIMAT__ID integer NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_CLIMAT IS 'Climat';
COMMENT ON COLUMN INF.INF_CLIMAT.INF_CLIMAT__INFO IS 'Commentaire';
COMMENT ON COLUMN INF.INF_CLIMAT.INF_CLIMAT__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_CLIMAT.INF_CLIMAT__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_CLIMAT.INF_CLIMAT__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CLIMAT.INF_CD_CLIMAT__ID IS 'Identifiant code climat';
COMMENT ON COLUMN INF.INF_CLIMAT.INF_CHAUSSEE__ID IS 'Identifiant3';

-- Table INF.INF_CD_AMENAGEMENT -> Référentiel Code aménagement
CREATE TABLE INF.INF_CD_AMENAGEMENT
(
INF_CD_AMENAGEMENT__CODE character varying(50) NOT NULL,
INF_CD_AMENAGEMENT__ID serial NOT NULL,
INF_CD_AMENAGEMENT__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_AMENAGEMENT IS 'Code aménagement';
COMMENT ON COLUMN INF.INF_CD_AMENAGEMENT.INF_CD_AMENAGEMENT__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_AMENAGEMENT.INF_CD_AMENAGEMENT__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_AMENAGEMENT.INF_CD_AMENAGEMENT__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_BIFURCATION -> Référentiel Code bifurcation
CREATE TABLE INF.INF_CD_BIFURCATION
(
INF_CD_BIFURCATION__CODE character varying(50) NOT NULL,
INF_CD_BIFURCATION__ID serial NOT NULL,
INF_CD_BIFURCATION__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_BIFURCATION IS 'Code bifurcation';
COMMENT ON COLUMN INF.INF_CD_BIFURCATION.INF_CD_BIFURCATION__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_BIFURCATION.INF_CD_BIFURCATION__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_BIFURCATION.INF_CD_BIFURCATION__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_CLIMAT -> Référentiel Code climat
CREATE TABLE INF.INF_CD_CLIMAT
(
INF_CD_CLIMAT__CODE character varying(50) NOT NULL,
INF_CD_CLIMAT__ID serial NOT NULL,
INF_CD_CLIMAT__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_CLIMAT IS 'Code climat';
COMMENT ON COLUMN INF.INF_CD_CLIMAT.INF_CD_CLIMAT__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_CLIMAT.INF_CD_CLIMAT__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_CLIMAT.INF_CD_CLIMAT__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_DEC -> Référentiel Code découpage
CREATE TABLE INF.INF_CD_DEC
(
INF_CD_DEC__CODE character varying(50) NOT NULL,
INF_CD_DEC__ID serial NOT NULL,
INF_FAM_DEC__ID integer NOT NULL,
INF_CD_DEC__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_DEC IS 'Code découpage';
COMMENT ON COLUMN INF.INF_CD_DEC.INF_CD_DEC__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_DEC.INF_CD_DEC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_DEC.INF_FAM_DEC__ID IS 'Identifiant famille découpage';
COMMENT ON COLUMN INF.INF_CD_DEC.INF_CD_DEC__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_DOC -> Référentiel Code document
CREATE TABLE INF.INF_CD_DOC
(
INF_CD_DOC__CODE character varying(50) NOT NULL,
INF_CD_DOC__ID serial NOT NULL,
INF_CD_DOC__LIBELLE character varying(255),
INF_CD_DOC__PATH character varying(255) NOT NULL
);
COMMENT ON TABLE INF.INF_CD_DOC IS 'Code document';
COMMENT ON COLUMN INF.INF_CD_DOC.INF_CD_DOC__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_DOC.INF_CD_DOC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_DOC.INF_CD_DOC__LIBELLE IS 'Libellé';
COMMENT ON COLUMN INF.INF_CD_DOC.INF_CD_DOC__PATH IS 'Répertoire';

-- Table INF.INF_CD_ECLAIRAGE -> Référentiel Code éclairage
CREATE TABLE INF.INF_CD_ECLAIRAGE
(
INF_CD_ECLAIRAGE__CODE character varying(50) NOT NULL,
INF_CD_ECLAIRAGE__ID serial NOT NULL,
INF_CD_ECLAIRAGE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_ECLAIRAGE IS 'Code éclairage';
COMMENT ON COLUMN INF.INF_CD_ECLAIRAGE.INF_CD_ECLAIRAGE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_ECLAIRAGE.INF_CD_ECLAIRAGE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_ECLAIRAGE.INF_CD_ECLAIRAGE__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_GARE -> Référentiel Code gare
CREATE TABLE INF.INF_CD_GARE
(
INF_CD_GARE__CODE character varying(50) NOT NULL,
INF_CD_GARE__ID serial NOT NULL,
INF_CD_GARE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_GARE IS 'Code gare';
COMMENT ON COLUMN INF.INF_CD_GARE.INF_CD_GARE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_GARE.INF_CD_GARE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_GARE.INF_CD_GARE__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_OCCUPANT -> Référentiel Code occupant
CREATE TABLE INF.INF_CD_OCCUPANT
(
INF_CD_OCCUPANT__CODE character varying(50) NOT NULL,
INF_CD_OCCUPANT__ID serial NOT NULL,
INF_CD_OCCUPANT__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_OCCUPANT IS 'Code occupant';
COMMENT ON COLUMN INF.INF_CD_OCCUPANT.INF_CD_OCCUPANT__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_OCCUPANT.INF_CD_OCCUPANT__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_OCCUPANT.INF_CD_OCCUPANT__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_OCCUPATION -> Référentiel Code occupation
CREATE TABLE INF.INF_CD_OCCUPATION
(
INF_CD_OCCUPATION__CODE character varying(50) NOT NULL,
INF_CD_OCCUPATION__ID serial NOT NULL,
INF_CD_OCCUPATION__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_OCCUPATION IS 'Code occupation';
COMMENT ON COLUMN INF.INF_CD_OCCUPATION.INF_CD_OCCUPATION__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_OCCUPATION.INF_CD_OCCUPATION__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_OCCUPATION.INF_CD_OCCUPATION__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_PT_SING -> Référentiel Code point singulier
CREATE TABLE INF.INF_CD_PT_SING
(
INF_CD_PT_SING__CODE character varying(50) NOT NULL,
INF_CD_PT_SING__ID serial NOT NULL,
INF_CD_PT_SING__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_PT_SING IS 'Code point singulier';
COMMENT ON COLUMN INF.INF_CD_PT_SING.INF_CD_PT_SING__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_PT_SING.INF_CD_PT_SING__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_PT_SING.INF_CD_PT_SING__LIBELLE IS 'Libelle';

-- Table INF.INF_CD_POSIT -> Référentiel Code position
CREATE TABLE INF.INF_CD_POSIT
(
INF_CD_POSIT__ID serial NOT NULL,
INF_CD_POSIT__ORDRE integer,
INF_CD_POSIT__POSITION integer NOT NULL
);
COMMENT ON TABLE INF.INF_CD_POSIT IS 'Code position';
COMMENT ON COLUMN INF.INF_CD_POSIT.INF_CD_POSIT__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_POSIT.INF_CD_POSIT__ORDRE IS 'Ordre';
COMMENT ON COLUMN INF.INF_CD_POSIT.INF_CD_POSIT__POSITION IS 'Position';

-- Table INF.INF_CD_SECURITE -> Référentiel Code sécurité
CREATE TABLE INF.INF_CD_SECURITE
(
INF_CD_SECURITE__CODE character varying(50) NOT NULL,
INF_CD_SECURITE__ID serial NOT NULL,
INF_CD_SECURITE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_SECURITE IS 'Code sécurité';
COMMENT ON COLUMN INF.INF_CD_SECURITE.INF_CD_SECURITE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_SECURITE.INF_CD_SECURITE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_SECURITE.INF_CD_SECURITE__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_SENSIBLE -> Référentiel Code sensibilité
CREATE TABLE INF.INF_CD_SENSIBLE
(
INF_CD_SENSIBLE__CODE character varying(50) NOT NULL,
INF_CD_SENSIBLE__ID serial NOT NULL,
INF_CD_SENSIBLE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_SENSIBLE IS 'Code sensibilité';
COMMENT ON COLUMN INF.INF_CD_SENSIBLE.INF_CD_SENSIBLE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_SENSIBLE.INF_CD_SENSIBLE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_SENSIBLE.INF_CD_SENSIBLE__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_DASHBOARD -> Référentiel Code tableau de bord
CREATE TABLE INF.INF_CD_DASHBOARD
(
INF_CD_DASHBOARD__CODE character varying(50) NOT NULL,
INF_CD_DASHBOARD__ID serial NOT NULL,
INF_CD_DASHBOARD__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_DASHBOARD IS 'Code tableau de bord';
COMMENT ON COLUMN INF.INF_CD_DASHBOARD.INF_CD_DASHBOARD__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_DASHBOARD.INF_CD_DASHBOARD__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_DASHBOARD.INF_CD_DASHBOARD__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_TALUS -> Référentiel Code talus
CREATE TABLE INF.INF_CD_TALUS
(
INF_CD_TALUS__CODE character varying(50) NOT NULL,
INF_CD_TALUS__ID serial NOT NULL,
INF_CD_TALUS__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_TALUS IS 'Code talus';
COMMENT ON COLUMN INF.INF_CD_TALUS.INF_CD_TALUS__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_TALUS.INF_CD_TALUS__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_TALUS.INF_CD_TALUS__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_TPC -> Référentiel Code TPC
CREATE TABLE INF.INF_CD_TPC
(
INF_CD_TPC__CODE character varying(50) NOT NULL,
INF_CD_TPC__ID serial NOT NULL,
INF_CD_TPC__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_TPC IS 'Code TPC';
COMMENT ON COLUMN INF.INF_CD_TPC.INF_CD_TPC__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_TPC.INF_CD_TPC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_TPC.INF_CD_TPC__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_VOIE -> Référentiel Code voie
CREATE TABLE INF.INF_CD_VOIE
(
INF_CD_VOIE__CODE character varying(50) NOT NULL,
INF_CD_VOIE__COULEUR character varying(15),
INF_CD_VOIE__ID serial NOT NULL,
INF_CD_VOIE__LIBELLE character varying(200),
INF_CD_VOIE__POSITION integer NOT NULL,
INF_CD_VOIE__ROULABLE boolean NOT NULL
);
COMMENT ON TABLE INF.INF_CD_VOIE IS 'Code voie';
COMMENT ON COLUMN INF.INF_CD_VOIE.INF_CD_VOIE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_VOIE.INF_CD_VOIE__COULEUR IS 'Couleur';
COMMENT ON COLUMN INF.INF_CD_VOIE.INF_CD_VOIE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_VOIE.INF_CD_VOIE__LIBELLE IS 'Libellé';
COMMENT ON COLUMN INF.INF_CD_VOIE.INF_CD_VOIE__POSITION IS 'Position';
COMMENT ON COLUMN INF.INF_CD_VOIE.INF_CD_VOIE__ROULABLE IS 'Roulable';

-- Table INF.INF_CONTACT_CLS -> Référentiel Contact des classeurs
CREATE TABLE INF.INF_CONTACT_CLS
(
INF_CONTACT_CLS__ID serial NOT NULL,
INF_CLS__ID integer NOT NULL,
INF_CONTACT__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_CONTACT_CLS IS 'Contact des classeurs';
COMMENT ON COLUMN INF.INF_CONTACT_CLS.INF_CONTACT_CLS__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CONTACT_CLS.INF_CLS__ID IS 'Identifiant classeur';
COMMENT ON COLUMN INF.INF_CONTACT_CLS.INF_CONTACT__ID IS 'Identifiant contact';

-- Table INF.INF_CONTACT -> Référentiel Contacts
CREATE TABLE INF.INF_CONTACT
(
INF_CONTACT__ADRESSE character varying(500),
INF_CONTACT__CODE_POSTAL character varying(10),
INF_CONTACT__ID serial NOT NULL,
INF_CONTACT__MAIL character varying(200),
INF_CONTACT__NOM character varying(200) NOT NULL,
INF_CONTACT__PRENOM character varying(200) NOT NULL,
INF_CONTACT__TEL_FIXE character varying(30),
INF_CONTACT__TEL_MOBILE character varying(30),
INF_CONTACT__VILLE character varying(200)
);
COMMENT ON TABLE INF.INF_CONTACT IS 'Contacts';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__ADRESSE IS 'Adresse';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__CODE_POSTAL IS 'Code postal';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__MAIL IS 'Mail';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__NOM IS 'Nom';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__PRENOM IS 'Prénom';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__TEL_FIXE IS 'Téléphone fixe';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__TEL_MOBILE IS 'Téléphone mobile';
COMMENT ON COLUMN INF.INF_CONTACT.INF_CONTACT__VILLE IS 'Ville';

-- Table INF.INF_DOC -> Référentiel Document
CREATE TABLE INF.INF_DOC
(
INF_DOC__FILENAME character varying(200) NOT NULL,
INF_DOC__ID serial NOT NULL,
INF_CD_DOC__ID integer NOT NULL,
INF_DOC__INFO character varying(500),
INF_DOC__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_DOC IS 'Document';
COMMENT ON COLUMN INF.INF_DOC.INF_DOC__FILENAME IS 'Fichier';
COMMENT ON COLUMN INF.INF_DOC.INF_DOC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_DOC.INF_CD_DOC__ID IS 'Identifiant2';
COMMENT ON COLUMN INF.INF_DOC.INF_DOC__INFO IS 'Informations';
COMMENT ON COLUMN INF.INF_DOC.INF_DOC__LIBELLE IS 'Libellé';

-- Table INF.INF_DOC_CLS -> Référentiel Document des classeurs
CREATE TABLE INF.INF_DOC_CLS
(
INF_DOC_CLS__DEFAUT boolean NOT NULL,
INF_DOC_CLS__ID serial NOT NULL,
INF_CLS__ID integer NOT NULL,
INF_DOC__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_DOC_CLS IS 'Document des classeurs';
COMMENT ON COLUMN INF.INF_DOC_CLS.INF_DOC_CLS__DEFAUT IS 'Document par défaut';
COMMENT ON COLUMN INF.INF_DOC_CLS.INF_DOC_CLS__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_DOC_CLS.INF_CLS__ID IS 'Identifiant classeur';
COMMENT ON COLUMN INF.INF_DOC_CLS.INF_DOC__ID IS 'Identifiant document';

-- Table INF.INF_ECLAIRAGE -> Référentiel Eclairage
CREATE TABLE INF.INF_ECLAIRAGE
(
INF_ECLAIRAGE__ABS_DEB integer NOT NULL,
INF_ECLAIRAGE__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_ECLAIRAGE__ID integer NOT NULL,
INF_CD_POSIT__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_ECLAIRAGE IS 'Eclairage';
COMMENT ON COLUMN INF.INF_ECLAIRAGE.INF_ECLAIRAGE__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_ECLAIRAGE.INF_ECLAIRAGE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_ECLAIRAGE.INF_CHAUSSEE__ID IS 'Identifiant chassée';
COMMENT ON COLUMN INF.INF_ECLAIRAGE.INF_CD_ECLAIRAGE__ID IS 'Identifiant code éclairage';
COMMENT ON COLUMN INF.INF_ECLAIRAGE.INF_CD_POSIT__ID IS 'Identifiant code position';

-- Table INF.INF_FAM_DEC -> Référentiel Famille découpage
CREATE TABLE INF.INF_FAM_DEC
(
INF_FAM_DEC__CODE character varying(50) NOT NULL,
INF_FAM_DEC__ID serial NOT NULL,
INF_FAM_DEC__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_FAM_DEC IS 'Famille découpage';
COMMENT ON COLUMN INF.INF_FAM_DEC.INF_FAM_DEC__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_FAM_DEC.INF_FAM_DEC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_FAM_DEC.INF_FAM_DEC__LIBELLE IS 'Libellé';

-- Table INF.INF_GARE -> Référentiel Gare
CREATE TABLE INF.INF_GARE
(
INF_GARE__INFO character varying(500),
INF_GARE__DATE_MS date,
INF_GARE__ABS_DEB integer NOT NULL,
INF_GARE__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_GARE__ID integer NOT NULL,
INF_GARE__NUM_EXPLOIT character varying(50),
INF_GARE__NB_SORTIE integer,
INF_GARE__NB_ENTREE integer,
INF_GARE__NB_MIXTE integer,
INF_GARE__NB_TSA integer,
INF_GARE__NOM character varying(200)
);
COMMENT ON TABLE INF.INF_GARE IS 'Gare';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__INFO IS 'Commentaire';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__DATE_MS IS 'Date MS';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_GARE.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_GARE.INF_CD_GARE__ID IS 'Identifiant code gare';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__NUM_EXPLOIT IS 'N° exploitation';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__NB_SORTIE IS 'Nb de voie de sortie';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__NB_ENTREE IS 'Nb de voie d''entrée';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__NB_MIXTE IS 'Nb de voie mixte';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__NB_TSA IS 'Nb de voie TSA';
COMMENT ON COLUMN INF.INF_GARE.INF_GARE__NOM IS 'Nom';

-- Table INF.INF_LIAISON -> Référentiel Liaison
CREATE TABLE INF.INF_LIAISON
(
INF_LIAISON__CODE character varying(50) NOT NULL,
INF_LIAISON__ID serial NOT NULL,
INF_CD_LIAISON__ID integer NOT NULL,
INF_LIAISON__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_LIAISON IS 'Liaison';
COMMENT ON COLUMN INF.INF_LIAISON.INF_LIAISON__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_LIAISON.INF_LIAISON__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_LIAISON.INF_CD_LIAISON__ID IS 'Identifiant type liaison';
COMMENT ON COLUMN INF.INF_LIAISON.INF_LIAISON__LIBELLE IS 'Libellé';

-- Table INF.INF_OCCUPATION -> Référentiel Occupation
CREATE TABLE INF.INF_OCCUPATION
(
INF_OCCUPATION__INFO character varying(500),
INF_OCCUPATION__DATE_FG date,
INF_OCCUPATION__DATE_MS date,
INF_OCCUPATION__ABS_DEB integer NOT NULL,
INF_OCCUPATION__ABS_FIN integer,
INF_OCCUPATION__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_OCCUPANT__ID integer NOT NULL,
INF_CD_OCCUPATION__ID integer NOT NULL,
INF_OCCUPATION__TRAVERSE boolean
);
COMMENT ON TABLE INF.INF_OCCUPATION IS 'Occupation';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_OCCUPATION__INFO IS 'Commentaire';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_OCCUPATION__DATE_FG IS 'Date FG';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_OCCUPATION__DATE_MS IS 'Date MS';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_OCCUPATION__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_OCCUPATION__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_OCCUPATION__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_CD_OCCUPANT__ID IS 'Identifiant code occupant';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_CD_OCCUPATION__ID IS 'Identifiant code occupation';
COMMENT ON COLUMN INF.INF_OCCUPATION.INF_OCCUPATION__TRAVERSE IS 'Traversé';

-- Table INF.INF_PAVE_VOIE -> Référentiel Pavé voie
CREATE TABLE INF.INF_PAVE_VOIE
(
INF_PAVE_VOIE__DATE_MS date NOT NULL,
INF_PAVE_VOIE__ABS_DEB integer NOT NULL,
INF_PAVE_VOIE__ABS_FIN integer NOT NULL,
INF_PAVE_VOIE__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_VOIE__ID integer NOT NULL,
INF_PAVE_VOIE__LARGEUR real NOT NULL
);
COMMENT ON TABLE INF.INF_PAVE_VOIE IS 'Pavé voie';
COMMENT ON COLUMN INF.INF_PAVE_VOIE.INF_PAVE_VOIE__DATE_MS IS 'Date MS';
COMMENT ON COLUMN INF.INF_PAVE_VOIE.INF_PAVE_VOIE__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_PAVE_VOIE.INF_PAVE_VOIE__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_PAVE_VOIE.INF_PAVE_VOIE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_PAVE_VOIE.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_PAVE_VOIE.INF_CD_VOIE__ID IS 'Identifiant code voie';
COMMENT ON COLUMN INF.INF_PAVE_VOIE.INF_PAVE_VOIE__LARGEUR IS 'Largeur';

-- Table INF.INF_PK -> Référentiel PK Chantier
CREATE TABLE INF.INF_PK
(
INF_PK__ABS_CUM integer NOT NULL,
INF_PK__INTER integer NOT NULL,
INF_PK__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_PK__NUM integer NOT NULL
);
COMMENT ON TABLE INF.INF_PK IS 'PK Chantier';
COMMENT ON COLUMN INF.INF_PK.INF_PK__ABS_CUM IS 'Abscisse';
COMMENT ON COLUMN INF.INF_PK.INF_PK__INTER IS 'Distance inter PR';
COMMENT ON COLUMN INF.INF_PK.INF_PK__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_PK.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_PK.INF_PK__NUM IS 'N° de PR';

-- Table INF.INF_PT_SING -> Référentiel Point singulier
CREATE TABLE INF.INF_PT_SING
(
INF_PT_SING__INFO character varying(500),
INF_PT_SING__ABS_DEB integer NOT NULL,
INF_PT_SING__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_PT_SING__ID integer NOT NULL,
INF_PT_SING__LIBELLE character varying(200),
INF_PT_SING__NOM character varying(100)
);
COMMENT ON TABLE INF.INF_PT_SING IS 'Point singulier';
COMMENT ON COLUMN INF.INF_PT_SING.INF_PT_SING__INFO IS 'Commentaire';
COMMENT ON COLUMN INF.INF_PT_SING.INF_PT_SING__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_PT_SING.INF_PT_SING__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_PT_SING.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_PT_SING.INF_CD_PT_SING__ID IS 'Identifiant code point singulier';
COMMENT ON COLUMN INF.INF_PT_SING.INF_PT_SING__LIBELLE IS 'Libellé';
COMMENT ON COLUMN INF.INF_PT_SING.INF_PT_SING__NOM IS 'Nom d''usage';

-- Table INF.INF_PRESTATAIRE -> Référentiel Prestataire
CREATE TABLE INF.INF_PRESTATAIRE
(
INF_PRESTATAIRE__CODE character varying(50) NOT NULL,
INF_PRESTATAIRE__ID serial NOT NULL,
INF_CD_PRESTATAIRE__ID integer NOT NULL,
INF_PRESTATAIRE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_PRESTATAIRE IS 'Prestataire';
COMMENT ON COLUMN INF.INF_PRESTATAIRE.INF_PRESTATAIRE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_PRESTATAIRE.INF_PRESTATAIRE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_PRESTATAIRE.INF_CD_PRESTATAIRE__ID IS 'Identifiant2';
COMMENT ON COLUMN INF.INF_PRESTATAIRE.INF_PRESTATAIRE__LIBELLE IS 'Libellé';

-- Table INF.INF_REPARTITION_TRAFIC -> Référentiel Répartition trafic
CREATE TABLE INF.INF_REPARTITION_TRAFIC
(
INF_REPARTITION_TRAFIC__PC_PL real,
INF_REPARTITION_TRAFIC__ANNEE integer NOT NULL,
INF_REPARTITION_TRAFIC__ABS_DEB integer NOT NULL,
INF_REPARTITION_TRAFIC__ABS_FIN integer,
INF_REPARTITION_TRAFIC__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_REPARTITION_TRAFIC IS 'Répartition trafic';
COMMENT ON COLUMN INF.INF_REPARTITION_TRAFIC.INF_REPARTITION_TRAFIC__PC_PL IS '% Poid lourd';
COMMENT ON COLUMN INF.INF_REPARTITION_TRAFIC.INF_REPARTITION_TRAFIC__ANNEE IS 'Année';
COMMENT ON COLUMN INF.INF_REPARTITION_TRAFIC.INF_REPARTITION_TRAFIC__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_REPARTITION_TRAFIC.INF_REPARTITION_TRAFIC__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_REPARTITION_TRAFIC.INF_REPARTITION_TRAFIC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_REPARTITION_TRAFIC.INF_CHAUSSEE__ID IS 'Identifiant chaussée';

-- Table INF.INF_REPERE -> Référentiel Repère
CREATE TABLE INF.INF_REPERE
(
INF_REPERE__ABS_CUM integer NOT NULL,
INF_REPERE__INTER integer NOT NULL,
INF_REPERE__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_REPERE__NUM integer NOT NULL
);
COMMENT ON TABLE INF.INF_REPERE IS 'Repère';
COMMENT ON COLUMN INF.INF_REPERE.INF_REPERE__ABS_CUM IS 'Abscisse';
COMMENT ON COLUMN INF.INF_REPERE.INF_REPERE__INTER IS 'Distance inter PR';
COMMENT ON COLUMN INF.INF_REPERE.INF_REPERE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_REPERE.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_REPERE.INF_REPERE__NUM IS 'N° de PR';

-- Table INF.INF_SECTION_TRAFIC -> Référentiel Section trafic
CREATE TABLE INF.INF_SECTION_TRAFIC
(
INF_SECTION_TRAFIC__ABOUT character varying(200),
INF_SECTION_TRAFIC__ABS_DEB integer NOT NULL,
INF_SECTION_TRAFIC__ABS_FIN integer,
INF_SECTION_TRAFIC__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_TRAFIC__ID integer NOT NULL,
INF_SECTION_TRAFIC__TENANT character varying(200)
);
COMMENT ON TABLE INF.INF_SECTION_TRAFIC IS 'Section trafic';
COMMENT ON COLUMN INF.INF_SECTION_TRAFIC.INF_SECTION_TRAFIC__ABOUT IS 'Aboutissant';
COMMENT ON COLUMN INF.INF_SECTION_TRAFIC.INF_SECTION_TRAFIC__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_SECTION_TRAFIC.INF_SECTION_TRAFIC__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_SECTION_TRAFIC.INF_SECTION_TRAFIC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_SECTION_TRAFIC.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_SECTION_TRAFIC.INF_CD_TRAFIC__ID IS 'Identifiant classe trafic';
COMMENT ON COLUMN INF.INF_SECTION_TRAFIC.INF_SECTION_TRAFIC__TENANT IS 'Tenant';

-- Table INF.INF_SECURITE -> Référentiel Sécurité
CREATE TABLE INF.INF_SECURITE
(
INF_SECURITE__ABS_DEB integer NOT NULL,
INF_SECURITE__ABS_FIN integer,
INF_SECURITE__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_POSIT__ID integer NOT NULL,
INF_CD_SECURITE__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_SECURITE IS 'Sécurité';
COMMENT ON COLUMN INF.INF_SECURITE.INF_SECURITE__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_SECURITE.INF_SECURITE__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_SECURITE.INF_SECURITE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_SECURITE.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_SECURITE.INF_CD_POSIT__ID IS 'Identifiant code position';
COMMENT ON COLUMN INF.INF_SECURITE.INF_CD_SECURITE__ID IS 'Identifiant code sécurité';

-- Table INF.INF_SENSIBLE -> Référentiel Sensibilité
CREATE TABLE INF.INF_SENSIBLE
(
INF_SENSIBLE__ABS_DEB integer NOT NULL,
INF_SENSIBLE__ABS_FIN integer,
INF_SENSIBLE__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_SENSIBLE__ID integer NOT NULL,
INF_SENSIBLE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_SENSIBLE IS 'Sensibilité';
COMMENT ON COLUMN INF.INF_SENSIBLE.INF_SENSIBLE__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_SENSIBLE.INF_SENSIBLE__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_SENSIBLE.INF_SENSIBLE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_SENSIBLE.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_SENSIBLE.INF_CD_SENSIBLE__ID IS 'Identifiant code sensible';
COMMENT ON COLUMN INF.INF_SENSIBLE.INF_SENSIBLE__LIBELLE IS 'Libellé';

-- Table INF.INF_DASHBOARD -> Référentiel Tableau de bord
CREATE TABLE INF.INF_DASHBOARD
(
INF_DASHBOARD__CODE character varying(50) NOT NULL,
INF_DASHBOARD__ID serial NOT NULL,
INF_DASHBOARD__ID_PARENT integer,
INF_CD_DASHBOARD__ID integer NOT NULL,
INF_DASHBOARD__LIBELLE character varying(200) NOT NULL,
INF_DASHBOARD__ORDRE integer NOT NULL
);
COMMENT ON TABLE INF.INF_DASHBOARD IS 'Tableau de bord';
COMMENT ON COLUMN INF.INF_DASHBOARD.INF_DASHBOARD__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_DASHBOARD.INF_DASHBOARD__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_DASHBOARD.INF_DASHBOARD__ID_PARENT IS 'Identifiant parent';
COMMENT ON COLUMN INF.INF_DASHBOARD.INF_CD_DASHBOARD__ID IS 'Identifiant2';
COMMENT ON COLUMN INF.INF_DASHBOARD.INF_DASHBOARD__LIBELLE IS 'Libellé';
COMMENT ON COLUMN INF.INF_DASHBOARD.INF_DASHBOARD__ORDRE IS 'Ordre';

-- Table INF.INF_TALUS -> Référentiel Talus
CREATE TABLE INF.INF_TALUS
(
INF_TALUS__ABS_DEB integer NOT NULL,
INF_TALUS__ABS_FIN integer,
INF_TALUS__HAUTEUR real,
INF_TALUS__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_TALUS__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_TALUS IS 'Talus';
COMMENT ON COLUMN INF.INF_TALUS.INF_TALUS__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_TALUS.INF_TALUS__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_TALUS.INF_TALUS__HAUTEUR IS 'Hauteur';
COMMENT ON COLUMN INF.INF_TALUS.INF_TALUS__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_TALUS.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_TALUS.INF_CD_TALUS__ID IS 'Identifiant code talus';

-- Table INF.INF_TPC -> Référentiel Terre plein central
CREATE TABLE INF.INF_TPC
(
INF_TPC__ABS_DEB integer NOT NULL,
INF_TPC__ABS_FIN integer NOT NULL,
INF_TPC__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_TPC__ID integer NOT NULL,
INF_TPC__LARGEUR real
);
COMMENT ON TABLE INF.INF_TPC IS 'Terre plein central';
COMMENT ON COLUMN INF.INF_TPC.INF_TPC__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_TPC.INF_TPC__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_TPC.INF_TPC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_TPC.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_TPC.INF_CD_TPC__ID IS 'Identifiant code TPC';
COMMENT ON COLUMN INF.INF_TPC.INF_TPC__LARGEUR IS 'Largeur';

-- Table INF.INF_TR_DEC -> Référentiel Tronçons découpage
CREATE TABLE INF.INF_TR_DEC
(
INF_TR_DEC__ABS_DEB integer NOT NULL,
INF_TR_DEC__ABS_FIN integer NOT NULL,
INF_TR_DEC__ID serial NOT NULL,
INF_CHAUSSEE__ID integer NOT NULL,
INF_CD_DEC__ID integer NOT NULL
);
COMMENT ON TABLE INF.INF_TR_DEC IS 'Tronçons découpage';
COMMENT ON COLUMN INF.INF_TR_DEC.INF_TR_DEC__ABS_DEB IS 'Début';
COMMENT ON COLUMN INF.INF_TR_DEC.INF_TR_DEC__ABS_FIN IS 'Fin';
COMMENT ON COLUMN INF.INF_TR_DEC.INF_TR_DEC__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_TR_DEC.INF_CHAUSSEE__ID IS 'Identifiant chaussée';
COMMENT ON COLUMN INF.INF_TR_DEC.INF_CD_DEC__ID IS 'Identifiant code découpage';

-- Table INF.INF_CD_AIRE -> Référentiel Type Aires
CREATE TABLE INF.INF_CD_AIRE
(
INF_CD_AIRE__CODE character varying(50) NOT NULL,
INF_CD_AIRE__ID serial NOT NULL,
INF_CD_AIRE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_AIRE IS 'Type Aires';
COMMENT ON COLUMN INF.INF_CD_AIRE.INF_CD_AIRE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_AIRE.INF_CD_AIRE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_AIRE.INF_CD_AIRE__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_LIAISON -> Référentiel Type liaison
CREATE TABLE INF.INF_CD_LIAISON
(
INF_CD_LIAISON__CODE character varying(50) NOT NULL,
INF_CD_LIAISON__COULEUR character varying(15),
INF_CD_LIAISON__ID serial NOT NULL,
INF_CD_LIAISON__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_LIAISON IS 'Type liaison';
COMMENT ON COLUMN INF.INF_CD_LIAISON.INF_CD_LIAISON__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_LIAISON.INF_CD_LIAISON__COULEUR IS 'Couleur';
COMMENT ON COLUMN INF.INF_CD_LIAISON.INF_CD_LIAISON__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_LIAISON.INF_CD_LIAISON__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_PLACE -> Référentiel Type parking
CREATE TABLE INF.INF_CD_PLACE
(
INF_CD_PLACE__CODE character varying(50) NOT NULL,
INF_CD_PLACE__ID serial NOT NULL,
INF_CD_PLACE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_PLACE IS 'Type parking';
COMMENT ON COLUMN INF.INF_CD_PLACE.INF_CD_PLACE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_PLACE.INF_CD_PLACE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_PLACE.INF_CD_PLACE__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_PRESTATAIRE -> Référentiel Type Prestataire
CREATE TABLE INF.INF_CD_PRESTATAIRE
(
INF_CD_PRESTATAIRE__CODE character varying(50) NOT NULL,
INF_CD_PRESTATAIRE__ID serial NOT NULL,
INF_CD_PRESTATAIRE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_PRESTATAIRE IS 'Type Prestataire';
COMMENT ON COLUMN INF.INF_CD_PRESTATAIRE.INF_CD_PRESTATAIRE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_PRESTATAIRE.INF_CD_PRESTATAIRE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_PRESTATAIRE.INF_CD_PRESTATAIRE__LIBELLE IS 'Libellé';

-- Table INF.INF_CD_SERVICE -> Référentiel Type Service
CREATE TABLE INF.INF_CD_SERVICE
(
INF_CD_SERVICE__CODE character varying(50) NOT NULL,
INF_CD_SERVICE__ID serial NOT NULL,
INF_CD_SERVICE__LIBELLE character varying(200)
);
COMMENT ON TABLE INF.INF_CD_SERVICE IS 'Type Service';
COMMENT ON COLUMN INF.INF_CD_SERVICE.INF_CD_SERVICE__CODE IS 'Code';
COMMENT ON COLUMN INF.INF_CD_SERVICE.INF_CD_SERVICE__ID IS 'Identifiant';
COMMENT ON COLUMN INF.INF_CD_SERVICE.INF_CD_SERVICE__LIBELLE IS 'Libellé';

-- Table PRF.PRF_LANG -> Gestion des utilisateurs Langue
CREATE TABLE PRF.PRF_LANG
(
PRF_LANG__KEY character varying(200) NOT NULL,
PRF_LANG__CODE_ISO character varying(3) NOT NULL,
PRF_LANG__ID serial NOT NULL,
PRF_LANG__VALEUR character varying(1000) NOT NULL
);
COMMENT ON TABLE PRF.PRF_LANG IS 'Langue';
COMMENT ON COLUMN PRF.PRF_LANG.PRF_LANG__KEY IS 'Clé';
COMMENT ON COLUMN PRF.PRF_LANG.PRF_LANG__CODE_ISO IS 'Code ISO';
COMMENT ON COLUMN PRF.PRF_LANG.PRF_LANG__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_LANG.PRF_LANG__VALEUR IS 'Valeur';

-- Table PRF.PRF_PARAM -> Gestion des utilisateurs Paramètres
CREATE TABLE PRF.PRF_PARAM
(
PRF_PARAM__CODE character varying(100) NOT NULL,
PRF_PARAM__ID serial NOT NULL,
PRF_SCHEMA__ID integer,
PRF_PARAM__VALEUR character varying(500) NOT NULL
);
COMMENT ON TABLE PRF.PRF_PARAM IS 'Paramètres';
COMMENT ON COLUMN PRF.PRF_PARAM.PRF_PARAM__CODE IS 'Code';
COMMENT ON COLUMN PRF.PRF_PARAM.PRF_PARAM__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_PARAM.PRF_SCHEMA__ID IS 'Identifiant2';
COMMENT ON COLUMN PRF.PRF_PARAM.PRF_PARAM__VALEUR IS 'Valeur';

-- Table PRF.PRF_PROFIL_RIGHT -> Gestion des utilisateurs Privilège des profils
CREATE TABLE PRF.PRF_PROFIL_RIGHT
(
PRF_PROFIL_RIGHT__ID serial NOT NULL,
PRF_RIGHT__ID integer NOT NULL,
PRF_PROFIL__ID integer NOT NULL
);
COMMENT ON TABLE PRF.PRF_PROFIL_RIGHT IS 'Privilège des profils';
COMMENT ON COLUMN PRF.PRF_PROFIL_RIGHT.PRF_PROFIL_RIGHT__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_PROFIL_RIGHT.PRF_RIGHT__ID IS 'Identifiant2';
COMMENT ON COLUMN PRF.PRF_PROFIL_RIGHT.PRF_PROFIL__ID IS 'Identifiant3';

-- Table PRF.PRF_RIGHT -> Gestion des utilisateurs Privilèges
CREATE TABLE PRF.PRF_RIGHT
(
PRF_RIGHT__CODE character varying(50) NOT NULL,
PRF_RIGHT__ID serial NOT NULL,
PRF_SCHEMA__ID integer NOT NULL,
PRF_RIGHT__LIBELLE character varying(200)
);
COMMENT ON TABLE PRF.PRF_RIGHT IS 'Privilèges';
COMMENT ON COLUMN PRF.PRF_RIGHT.PRF_RIGHT__CODE IS 'Code';
COMMENT ON COLUMN PRF.PRF_RIGHT.PRF_RIGHT__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_RIGHT.PRF_SCHEMA__ID IS 'Identifiant2';
COMMENT ON COLUMN PRF.PRF_RIGHT.PRF_RIGHT__LIBELLE IS 'Libellé';

-- Table PRF.PRF_USER_PROFIL -> Gestion des utilisateurs Profil des utilisateurs
CREATE TABLE PRF.PRF_USER_PROFIL
(
PRF_USER_PROFIL__ID serial NOT NULL,
PRF_PROFIL__ID integer NOT NULL,
PRF_USER__ID integer NOT NULL
);
COMMENT ON TABLE PRF.PRF_USER_PROFIL IS 'Profil des utilisateurs';
COMMENT ON COLUMN PRF.PRF_USER_PROFIL.PRF_USER_PROFIL__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_USER_PROFIL.PRF_PROFIL__ID IS 'Identifiant2';
COMMENT ON COLUMN PRF.PRF_USER_PROFIL.PRF_USER__ID IS 'Identifiant3';

-- Table PRF.PRF_PROFIL -> Gestion des utilisateurs Profils
CREATE TABLE PRF.PRF_PROFIL
(
PRF_PROFIL__CODE character varying(50),
PRF_PROFIL__ID serial NOT NULL,
PRF_SCHEMA__ID integer NOT NULL,
PRF_PROFIL__LIBELLE character varying(200)
);
COMMENT ON TABLE PRF.PRF_PROFIL IS 'Profils';
COMMENT ON COLUMN PRF.PRF_PROFIL.PRF_PROFIL__CODE IS 'Code';
COMMENT ON COLUMN PRF.PRF_PROFIL.PRF_PROFIL__ID IS 'Identifiant profil';
COMMENT ON COLUMN PRF.PRF_PROFIL.PRF_SCHEMA__ID IS 'Identifiant schéma';
COMMENT ON COLUMN PRF.PRF_PROFIL.PRF_PROFIL__LIBELLE IS 'Libellé';

-- Table PRF.PRF_SCHEMA -> Gestion des utilisateurs Schémas
CREATE TABLE PRF.PRF_SCHEMA
(
PRF_SCHEMA__ID serial NOT NULL,
PRF_SCHEMA__LIBELLE character varying(200),
PRF_SCHEMA__NAME character varying(50) NOT NULL
);
COMMENT ON TABLE PRF.PRF_SCHEMA IS 'Schémas';
COMMENT ON COLUMN PRF.PRF_SCHEMA.PRF_SCHEMA__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_SCHEMA.PRF_SCHEMA__LIBELLE IS 'Libellé';
COMMENT ON COLUMN PRF.PRF_SCHEMA.PRF_SCHEMA__NAME IS 'Nom';

-- Table PRF.PRF_PROFIL_TABLE -> Gestion des utilisateurs Table des profil
CREATE TABLE PRF.PRF_PROFIL_TABLE
(
PRF_PROFIL_TABLE__WRITE boolean NOT NULL,
PRF_PROFIL_TABLE__IMPORT boolean NOT NULL,
PRF_PROFIL_TABLE__ID serial NOT NULL,
PRF_PROFIL__ID integer NOT NULL,
PRF_TABLE__ID integer NOT NULL
);
COMMENT ON TABLE PRF.PRF_PROFIL_TABLE IS 'Table des profil';
COMMENT ON COLUMN PRF.PRF_PROFIL_TABLE.PRF_PROFIL_TABLE__WRITE IS 'Autoriser écriture';
COMMENT ON COLUMN PRF.PRF_PROFIL_TABLE.PRF_PROFIL_TABLE__IMPORT IS 'Autoriser import';
COMMENT ON COLUMN PRF.PRF_PROFIL_TABLE.PRF_PROFIL_TABLE__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_PROFIL_TABLE.PRF_PROFIL__ID IS 'Identifiant2';
COMMENT ON COLUMN PRF.PRF_PROFIL_TABLE.PRF_TABLE__ID IS 'Identifiant3';

-- Table PRF.PRF_TABLE -> Gestion des utilisateurs Tables
CREATE TABLE PRF.PRF_TABLE
(
PRF_TABLE__ID serial NOT NULL,
PRF_SCHEMA__ID integer NOT NULL,
PRF_TABLE__LIBELLE character varying(200),
PRF_TABLE__NAME character varying(50) NOT NULL
);
COMMENT ON TABLE PRF.PRF_TABLE IS 'Tables';
COMMENT ON COLUMN PRF.PRF_TABLE.PRF_TABLE__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_TABLE.PRF_SCHEMA__ID IS 'Identifiant schéma';
COMMENT ON COLUMN PRF.PRF_TABLE.PRF_TABLE__LIBELLE IS 'Libellé';
COMMENT ON COLUMN PRF.PRF_TABLE.PRF_TABLE__NAME IS 'Nom';

-- Table PRF.PRF_USER -> Gestion des utilisateurs Utilisateurs
CREATE TABLE PRF.PRF_USER
(
PRF_USER__ID serial NOT NULL,
PRF_USER__LOGIN character varying(50) NOT NULL,
PRF_USER__NOM character varying(100) NOT NULL,
PRF_USER__PASSSWORD character varying(50),
PRF_USER__PRENOM character varying(50) NOT NULL
);
COMMENT ON TABLE PRF.PRF_USER IS 'Utilisateurs';
COMMENT ON COLUMN PRF.PRF_USER.PRF_USER__ID IS 'Identifiant';
COMMENT ON COLUMN PRF.PRF_USER.PRF_USER__LOGIN IS 'Login';
COMMENT ON COLUMN PRF.PRF_USER.PRF_USER__NOM IS 'Nom';
COMMENT ON COLUMN PRF.PRF_USER.PRF_USER__PASSSWORD IS 'Passsword';
COMMENT ON COLUMN PRF.PRF_USER.PRF_USER__PRENOM IS 'Prénom';

-- Table SIG.SIG_LAYER -> Système d'information géographique Couche
CREATE TABLE SIG.SIG_LAYER
(
SIG_LAYER__ID serial NOT NULL,
SIG_CD_LAYER__ID integer NOT NULL,
SIG_LAYER__LIBELLE character varying(200) NOT NULL,
SIG_LAYER__MAP_ORDER integer NOT NULL
);
COMMENT ON TABLE SIG.SIG_LAYER IS 'Couche';
COMMENT ON COLUMN SIG.SIG_LAYER.SIG_LAYER__ID IS 'Identifiant';
COMMENT ON COLUMN SIG.SIG_LAYER.SIG_CD_LAYER__ID IS 'Identifiant type couche';
COMMENT ON COLUMN SIG.SIG_LAYER.SIG_LAYER__LIBELLE IS 'Libellé';
COMMENT ON COLUMN SIG.SIG_LAYER.SIG_LAYER__MAP_ORDER IS 'Ordre dans la carte';

-- Table SIG.SIG_NODE -> Système d'information géographique Noeud
CREATE TABLE SIG.SIG_NODE
(
SIG_NODE__ID serial NOT NULL,
SIG_LAYER__ID integer,
SIG_TEMPLATE__ID integer NOT NULL,
SIG_CD_NODE__ID integer NOT NULL,
SIG_NODE__LIBELLE character varying(200) NOT NULL,
SIG_NODE__PARENT_ID integer NOT NULL,
SIG_NODE__ORDER integer NOT NULL
);
COMMENT ON TABLE SIG.SIG_NODE IS 'Noeud';
COMMENT ON COLUMN SIG.SIG_NODE.SIG_NODE__ID IS 'Identifiant';
COMMENT ON COLUMN SIG.SIG_NODE.SIG_LAYER__ID IS 'Identifiant couche';
COMMENT ON COLUMN SIG.SIG_NODE.SIG_TEMPLATE__ID IS 'Identifiant template';
COMMENT ON COLUMN SIG.SIG_NODE.SIG_CD_NODE__ID IS 'Identifiant type noeud';
COMMENT ON COLUMN SIG.SIG_NODE.SIG_NODE__LIBELLE IS 'Libellé';
COMMENT ON COLUMN SIG.SIG_NODE.SIG_NODE__PARENT_ID IS 'Noeud parent';
COMMENT ON COLUMN SIG.SIG_NODE.SIG_NODE__ORDER IS 'Ordre';

-- Table SIG.SIG_TEMPLATE -> Système d'information géographique Template de carte
CREATE TABLE SIG.SIG_TEMPLATE
(
SIG_TEMPLATE__ID serial NOT NULL,
SIG_CD_TEMPLATE__ID integer NOT NULL,
SIG_TEMPLATE__LIBELLE character varying(200) NOT NULL
);
COMMENT ON TABLE SIG.SIG_TEMPLATE IS 'Template de carte';
COMMENT ON COLUMN SIG.SIG_TEMPLATE.SIG_TEMPLATE__ID IS 'Identifiant';
COMMENT ON COLUMN SIG.SIG_TEMPLATE.SIG_CD_TEMPLATE__ID IS 'Identifiant type template';
COMMENT ON COLUMN SIG.SIG_TEMPLATE.SIG_TEMPLATE__LIBELLE IS 'Libellé';

-- Table SIG.SIG_CD_LAYER -> Système d'information géographique Type de couche
CREATE TABLE SIG.SIG_CD_LAYER
(
SIG_CD_LAYER__CODE character varying(50) NOT NULL,
SIG_CD_LAYER__ID serial NOT NULL,
SIG_CD_LAYER__LIBELLE character varying(500)
);
COMMENT ON TABLE SIG.SIG_CD_LAYER IS 'Type de couche';
COMMENT ON COLUMN SIG.SIG_CD_LAYER.SIG_CD_LAYER__CODE IS 'Code';
COMMENT ON COLUMN SIG.SIG_CD_LAYER.SIG_CD_LAYER__ID IS 'Identifiant';
COMMENT ON COLUMN SIG.SIG_CD_LAYER.SIG_CD_LAYER__LIBELLE IS 'Libellé';

-- Table SIG.SIG_CD_NODE -> Système d'information géographique Type de noeud
CREATE TABLE SIG.SIG_CD_NODE
(
SIG_CD_NODE__CODE character varying(50) NOT NULL,
SIG_CD_NODE__ID serial NOT NULL,
SIG_CD_NODE__LIBELLE character varying(200)
);
COMMENT ON TABLE SIG.SIG_CD_NODE IS 'Type de noeud';
COMMENT ON COLUMN SIG.SIG_CD_NODE.SIG_CD_NODE__CODE IS 'Code';
COMMENT ON COLUMN SIG.SIG_CD_NODE.SIG_CD_NODE__ID IS 'Identifiant';
COMMENT ON COLUMN SIG.SIG_CD_NODE.SIG_CD_NODE__LIBELLE IS 'Libellé';

-- Table SIG.SIG_CD_TEMPLATE -> Système d'information géographique Type de template
CREATE TABLE SIG.SIG_CD_TEMPLATE
(
SIG_CD_TEMPLATE__CODE character varying(50) NOT NULL,
SIG_CD_TEMPLATE__ID serial NOT NULL,
SIG_CD_TEMPLATE__LIBELLE character varying(200)
);
COMMENT ON TABLE SIG.SIG_CD_TEMPLATE IS 'Type de template';
COMMENT ON COLUMN SIG.SIG_CD_TEMPLATE.SIG_CD_TEMPLATE__CODE IS 'Code';
COMMENT ON COLUMN SIG.SIG_CD_TEMPLATE.SIG_CD_TEMPLATE__ID IS 'Identifiant';
COMMENT ON COLUMN SIG.SIG_CD_TEMPLATE.SIG_CD_TEMPLATE__LIBELLE IS 'Libellé';

-- Clé primaires
ALTER TABLE INF.INF_ACCIDENT  ADD CONSTRAINT INF_ACCIDENT_PK PRIMARY KEY (INF_ACCIDENT__ID);
ALTER TABLE INF.INF_AIRE_PARKING  ADD CONSTRAINT INF_AIRE_PARKING_PK PRIMARY KEY (INF_AIRE_PARKING__ID);
ALTER TABLE INF.INF_AIRE_PRESTATAIRE  ADD CONSTRAINT INF_AIRE_PRESTATAIRE_PK PRIMARY KEY (INF_AIRE_PRESTATAIRE__ID);
ALTER TABLE INF.INF_AIRE_SERVICE  ADD CONSTRAINT INF_AIRE_SERVICE_PK PRIMARY KEY (INF_AIRE_SERVICE__ID);
ALTER TABLE INF.INF_AIRE  ADD CONSTRAINT INF_AIRE_PK PRIMARY KEY (INF_AIRE__ID);
ALTER TABLE INF.INF_AMENAGEMENT  ADD CONSTRAINT INF_AMENAGEMENT_PK PRIMARY KEY (INF_AMENAGEMENT__ID);
ALTER TABLE INF.INF_PR_OLD  ADD CONSTRAINT INF_PR_OLD_PK PRIMARY KEY (INF_PR_OLD__ID);
ALTER TABLE INF.INF_BIFURCATION  ADD CONSTRAINT INF_BIFURCATION_PK PRIMARY KEY (INF_BIFURCATION__ID);
ALTER TABLE INF.INF_BRETELLE  ADD CONSTRAINT INF_BRETELLE_PK PRIMARY KEY (INF_BRETELLE__ID);
ALTER TABLE INF.INF_CHAUSSEE  ADD CONSTRAINT INF_CHAUSSEE_PK PRIMARY KEY (INF_CHAUSSEE__ID);
ALTER TABLE INF.INF_CD_TRAFIC  ADD CONSTRAINT INF_CD_TRAFIC_PK PRIMARY KEY (INF_CD_TRAFIC__ID);
ALTER TABLE INF.INF_CLS  ADD CONSTRAINT INF_CLS_PK PRIMARY KEY (INF_CLS__ID);
ALTER TABLE INF.INF_CLIMAT  ADD CONSTRAINT INF_CLIMAT_PK PRIMARY KEY (INF_CLIMAT__ID);
ALTER TABLE INF.INF_CD_AMENAGEMENT  ADD CONSTRAINT INF_CD_AMENAGEMENT_PK PRIMARY KEY (INF_CD_AMENAGEMENT__ID);
ALTER TABLE INF.INF_CD_BIFURCATION  ADD CONSTRAINT INF_CD_BIFURCATION_PK PRIMARY KEY (INF_CD_BIFURCATION__ID);
ALTER TABLE INF.INF_CD_CLIMAT  ADD CONSTRAINT INF_CD_CLIMAT_PK PRIMARY KEY (INF_CD_CLIMAT__ID);
ALTER TABLE INF.INF_CD_DEC  ADD CONSTRAINT INF_CD_DEC_PK PRIMARY KEY (INF_CD_DEC__ID);
ALTER TABLE INF.INF_CD_DOC  ADD CONSTRAINT INF_CD_DOC_PK PRIMARY KEY (INF_CD_DOC__ID);
ALTER TABLE INF.INF_CD_ECLAIRAGE  ADD CONSTRAINT INF_CD_ECLAIRAGE_PK PRIMARY KEY (INF_CD_ECLAIRAGE__ID);
ALTER TABLE INF.INF_CD_GARE  ADD CONSTRAINT INF_CD_GARE_PK PRIMARY KEY (INF_CD_GARE__ID);
ALTER TABLE INF.INF_CD_OCCUPANT  ADD CONSTRAINT INF_CD_OCCUPANT_PK PRIMARY KEY (INF_CD_OCCUPANT__ID);
ALTER TABLE INF.INF_CD_OCCUPATION  ADD CONSTRAINT INF_CD_OCCUPATION_PK PRIMARY KEY (INF_CD_OCCUPATION__ID);
ALTER TABLE INF.INF_CD_PT_SING  ADD CONSTRAINT INF_CD_PT_SING_PK PRIMARY KEY (INF_CD_PT_SING__ID);
ALTER TABLE INF.INF_CD_POSIT  ADD CONSTRAINT INF_CD_POSIT_PK PRIMARY KEY (INF_CD_POSIT__ID);
ALTER TABLE INF.INF_CD_SECURITE  ADD CONSTRAINT INF_CD_SECURITE_PK PRIMARY KEY (INF_CD_SECURITE__ID);
ALTER TABLE INF.INF_CD_SENSIBLE  ADD CONSTRAINT INF_CD_SENSIBLE_PK PRIMARY KEY (INF_CD_SENSIBLE__ID);
ALTER TABLE INF.INF_CD_DASHBOARD  ADD CONSTRAINT IDENTIFIANT_1 PRIMARY KEY (INF_CD_DASHBOARD__ID);
ALTER TABLE INF.INF_CD_TALUS  ADD CONSTRAINT INF_CD_TALUS_PK PRIMARY KEY (INF_CD_TALUS__ID);
ALTER TABLE INF.INF_CD_TPC  ADD CONSTRAINT INF_CD_TPC_PK PRIMARY KEY (INF_CD_TPC__ID);
ALTER TABLE INF.INF_CD_VOIE  ADD CONSTRAINT INF_CD_VOIE_PK PRIMARY KEY (INF_CD_VOIE__ID);
ALTER TABLE INF.INF_CONTACT_CLS  ADD CONSTRAINT INF_CONTACT_CLS_PK PRIMARY KEY (INF_CONTACT_CLS__ID);
ALTER TABLE INF.INF_CONTACT  ADD CONSTRAINT INF_CONTACT_PK PRIMARY KEY (INF_CONTACT__ID);
ALTER TABLE INF.INF_DOC  ADD CONSTRAINT INF_DOC_PK PRIMARY KEY (INF_DOC__ID);
ALTER TABLE INF.INF_DOC_CLS  ADD CONSTRAINT INF_DOC_CLS_PK PRIMARY KEY (INF_DOC_CLS__ID);
ALTER TABLE INF.INF_ECLAIRAGE  ADD CONSTRAINT INF_ECLAIRAGE_PK PRIMARY KEY (INF_ECLAIRAGE__ID);
ALTER TABLE INF.INF_FAM_DEC  ADD CONSTRAINT INF_FAM_DEC_PK PRIMARY KEY (INF_FAM_DEC__ID);
ALTER TABLE INF.INF_GARE  ADD CONSTRAINT INF_GARE_PK PRIMARY KEY (INF_GARE__ID);
ALTER TABLE INF.INF_LIAISON  ADD CONSTRAINT INF_LIAISON_PK PRIMARY KEY (INF_LIAISON__ID);
ALTER TABLE INF.INF_OCCUPATION  ADD CONSTRAINT INF_OCCUPATION_PK PRIMARY KEY (INF_OCCUPATION__ID);
ALTER TABLE INF.INF_PAVE_VOIE  ADD CONSTRAINT INF_PAVE_VOIE_PK PRIMARY KEY (INF_PAVE_VOIE__ID);
ALTER TABLE INF.INF_PK  ADD CONSTRAINT INF_PK_PK PRIMARY KEY (INF_PK__ID);
ALTER TABLE INF.INF_PT_SING  ADD CONSTRAINT INF_PT_SING_PK PRIMARY KEY (INF_PT_SING__ID);
ALTER TABLE INF.INF_PRESTATAIRE  ADD CONSTRAINT INF_PRESTATAIRE_PK PRIMARY KEY (INF_PRESTATAIRE__ID);
ALTER TABLE INF.INF_REPARTITION_TRAFIC  ADD CONSTRAINT INF_REPARTITION_TRAFIC_PK PRIMARY KEY (INF_REPARTITION_TRAFIC__ID);
ALTER TABLE INF.INF_REPERE  ADD CONSTRAINT INF_REPERE_PK PRIMARY KEY (INF_REPERE__ID);
ALTER TABLE INF.INF_SECTION_TRAFIC  ADD CONSTRAINT INF_SECTION_TRAFIC_PK PRIMARY KEY (INF_SECTION_TRAFIC__ID);
ALTER TABLE INF.INF_SECURITE  ADD CONSTRAINT INF_SECURITE_PK PRIMARY KEY (INF_SECURITE__ID);
ALTER TABLE INF.INF_SENSIBLE  ADD CONSTRAINT INF_SENSIBLE_PK PRIMARY KEY (INF_SENSIBLE__ID);
ALTER TABLE INF.INF_DASHBOARD  ADD CONSTRAINT IDENTIFIANT_1 PRIMARY KEY (INF_DASHBOARD__ID);
ALTER TABLE INF.INF_TALUS  ADD CONSTRAINT INF_TALUS_PK PRIMARY KEY (INF_TALUS__ID);
ALTER TABLE INF.INF_TPC  ADD CONSTRAINT INF_TPC_PK PRIMARY KEY (INF_TPC__ID);
ALTER TABLE INF.INF_TR_DEC  ADD CONSTRAINT INF_TR_DEC_PK PRIMARY KEY (INF_TR_DEC__ID);
ALTER TABLE INF.INF_CD_AIRE  ADD CONSTRAINT INF_CD_AIRE_PK PRIMARY KEY (INF_CD_AIRE__ID);
ALTER TABLE INF.INF_CD_LIAISON  ADD CONSTRAINT INF_CD_LIAISON_PK PRIMARY KEY (INF_CD_LIAISON__ID);
ALTER TABLE INF.INF_CD_PLACE  ADD CONSTRAINT INF_CD_PLACE_PK PRIMARY KEY (INF_CD_PLACE__ID);
ALTER TABLE INF.INF_CD_PRESTATAIRE  ADD CONSTRAINT INF_CD_PRESTATAIRE_PK PRIMARY KEY (INF_CD_PRESTATAIRE__ID);
ALTER TABLE INF.INF_CD_SERVICE  ADD CONSTRAINT INF_CD_SERVICE_PK PRIMARY KEY (INF_CD_SERVICE__ID);
ALTER TABLE PRF.PRF_LANG  ADD CONSTRAINT PRF_LANG_PK PRIMARY KEY (PRF_LANG__ID);
ALTER TABLE PRF.PRF_PARAM  ADD CONSTRAINT PRF_PARAM_PK PRIMARY KEY (PRF_PARAM__ID);
ALTER TABLE PRF.PRF_PROFIL_RIGHT  ADD CONSTRAINT PRF_PROFIL_RIGHT_PK PRIMARY KEY (PRF_PROFIL_RIGHT__ID);
ALTER TABLE PRF.PRF_RIGHT  ADD CONSTRAINT PRF_RIGHT_PK PRIMARY KEY (PRF_RIGHT__ID);
ALTER TABLE PRF.PRF_USER_PROFIL  ADD CONSTRAINT PRF_USER_PROFIL_PK PRIMARY KEY (PRF_USER_PROFIL__ID);
ALTER TABLE PRF.PRF_PROFIL  ADD CONSTRAINT PRF_PROFIL_PK PRIMARY KEY (PRF_PROFIL__ID);
ALTER TABLE PRF.PRF_SCHEMA  ADD CONSTRAINT PRF_SCHEMA_PK PRIMARY KEY (PRF_SCHEMA__ID);
ALTER TABLE PRF.PRF_PROFIL_TABLE  ADD CONSTRAINT PRF_PROFIL_TABLE_PK PRIMARY KEY (PRF_PROFIL_TABLE__ID);
ALTER TABLE PRF.PRF_TABLE  ADD CONSTRAINT PRF_TABLE_PK PRIMARY KEY (PRF_TABLE__ID);
ALTER TABLE PRF.PRF_USER  ADD CONSTRAINT PRF_USER_PK PRIMARY KEY (PRF_USER__ID);
ALTER TABLE SIG.SIG_LAYER  ADD CONSTRAINT SIG_LAYER_PK PRIMARY KEY (SIG_LAYER__ID);
ALTER TABLE SIG.SIG_NODE  ADD CONSTRAINT SIG_NODE_PK PRIMARY KEY (SIG_NODE__ID);
ALTER TABLE SIG.SIG_TEMPLATE  ADD CONSTRAINT SIG_TEMPLATE_PK PRIMARY KEY (SIG_TEMPLATE__ID);
ALTER TABLE SIG.SIG_CD_LAYER  ADD CONSTRAINT SIG_CD_LAYER_PK PRIMARY KEY (SIG_CD_LAYER__ID);
ALTER TABLE SIG.SIG_CD_NODE  ADD CONSTRAINT SIG_CD_NODE_PK PRIMARY KEY (SIG_CD_NODE__ID);
ALTER TABLE SIG.SIG_CD_TEMPLATE  ADD CONSTRAINT SIG_CD_TEMPLATE_PK PRIMARY KEY (SIG_CD_TEMPLATE__ID);

-- Clé uniques
ALTER TABLE INF.INF_ACCIDENT  ADD CONSTRAINT INF_ACCIDENT__UK_REF UNIQUE (INF_ACCIDENT__ANNEE,INF_ACCIDENT__ABS_DEB,INF_CHAUSSEE__ID,INF_ACCIDENT__MOIS);
ALTER TABLE INF.INF_AIRE_PARKING  ADD CONSTRAINT INF_AIRE_PARKING_UK_REF UNIQUE (INF_AIRE__ID,INF_CD_PLACE__ID);
ALTER TABLE INF.INF_AIRE_PRESTATAIRE  ADD CONSTRAINT INF_AIRE_PRESTATAIRE_UK_REF UNIQUE (INF_AIRE__ID,INF_PRESTATAIRE__ID);
ALTER TABLE INF.INF_AIRE_SERVICE  ADD CONSTRAINT INF_AIRE_SERVICE_UK_REF UNIQUE (INF_AIRE__ID,INF_CD_SERVICE__ID);
ALTER TABLE INF.INF_AIRE  ADD CONSTRAINT INF_AIRE_UK_REF UNIQUE (INF_AIRE__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_AIRE__ID);
ALTER TABLE INF.INF_AMENAGEMENT  ADD CONSTRAINT INF_AMENAGEMENT_UK_REF UNIQUE (INF_AMENAGEMENT__DATE_DEB,INF_AMENAGEMENT__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_AMENAGEMENT__ID);
ALTER TABLE INF.INF_PR_OLD  ADD CONSTRAINT INF_PR_OLD_UK_REF UNIQUE (INF_PR_OLD__ABS_CUM,INF_CHAUSSEE__ID);
ALTER TABLE INF.INF_PR_OLD  ADD CONSTRAINT INF_PR_OLD_UK2 UNIQUE (INF_CHAUSSEE__ID,INF_PR_OLD__NUM);
ALTER TABLE INF.INF_BIFURCATION  ADD CONSTRAINT INF_BIFURCATION_UK_REF UNIQUE (INF_BIFURCATION__DATE_MS,INF_BIFURCATION__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_BIFURCATION__ID);
ALTER TABLE INF.INF_BRETELLE  ADD CONSTRAINT INF_BRETELLE_UK_REF UNIQUE (INF_BRETELLE__ABS_DEB,INF_CHAUSSEE__ID);
ALTER TABLE INF.INF_CHAUSSEE  ADD CONSTRAINT INF_CHAUSSEE_UK_REF UNIQUE (INF_CHAUSSEE__CODE,INF_LIAISON__ID);
ALTER TABLE INF.INF_CD_TRAFIC  ADD CONSTRAINT INF_CD_TRAFIC_UK_REF UNIQUE (INF_CD_TRAFIC__CODE);
ALTER TABLE INF.INF_CLIMAT  ADD CONSTRAINT INF_CLIMAT_UK_REF UNIQUE (INF_CLIMAT__ABS_DEB,INF_CD_CLIMAT__ID,INF_CHAUSSEE__ID);
ALTER TABLE INF.INF_CD_AMENAGEMENT  ADD CONSTRAINT INF_CD_AMENAGEMENT_UK_REF UNIQUE (INF_CD_AMENAGEMENT__CODE);
ALTER TABLE INF.INF_CD_BIFURCATION  ADD CONSTRAINT INF_CD_BIFURCATION__UK_REF UNIQUE (INF_CD_BIFURCATION__CODE);
ALTER TABLE INF.INF_CD_CLIMAT  ADD CONSTRAINT INF_CD_CLIMAT_UK_REF UNIQUE (INF_CD_CLIMAT__CODE);
ALTER TABLE INF.INF_CD_DEC  ADD CONSTRAINT INF_CD_DEC_UK_REF UNIQUE (INF_CD_DEC__CODE,INF_FAM_DEC__ID);
ALTER TABLE INF.INF_CD_ECLAIRAGE  ADD CONSTRAINT INF_CD_ECLAIRAGE_UK_REF UNIQUE (INF_CD_ECLAIRAGE__CODE);
ALTER TABLE INF.INF_CD_GARE  ADD CONSTRAINT INF_CD_GARE_UK_REF UNIQUE (INF_CD_GARE__CODE);
ALTER TABLE INF.INF_CD_OCCUPANT  ADD CONSTRAINT INF_CD_OCCUPANT_UK_REF UNIQUE (INF_CD_OCCUPANT__CODE);
ALTER TABLE INF.INF_CD_OCCUPATION  ADD CONSTRAINT INF_CD_OCCUPATION_UK_REF UNIQUE (INF_CD_OCCUPATION__CODE);
ALTER TABLE INF.INF_CD_PT_SING  ADD CONSTRAINT INF_CD_PT_SING_UK_REF UNIQUE (INF_CD_PT_SING__CODE);
ALTER TABLE INF.INF_CD_POSIT  ADD CONSTRAINT INF_CD_POSIT_UK_REF UNIQUE (INF_CD_POSIT__POSITION);
ALTER TABLE INF.INF_CD_SECURITE  ADD CONSTRAINT INF_CD_SECURITE_UK_REF UNIQUE (INF_CD_SECURITE__CODE);
ALTER TABLE INF.INF_CD_SENSIBLE  ADD CONSTRAINT INF_CD_SENSIBLE_UK_REF UNIQUE (INF_CD_SENSIBLE__CODE);
ALTER TABLE INF.INF_CD_TALUS  ADD CONSTRAINT INF_CD_TALUS_UK_REF UNIQUE (INF_CD_TALUS__CODE);
ALTER TABLE INF.INF_CD_TPC  ADD CONSTRAINT INF_CD_TPC_UK_REF UNIQUE (INF_CD_TPC__CODE);
ALTER TABLE INF.INF_CD_VOIE  ADD CONSTRAINT UK_CODE_VOIE UNIQUE (INF_CD_VOIE__CODE);
ALTER TABLE INF.INF_ECLAIRAGE  ADD CONSTRAINT INF_ECLAIRAGE_UK_REF UNIQUE (INF_ECLAIRAGE__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_ECLAIRAGE__ID,INF_CD_POSIT__ID);
ALTER TABLE INF.INF_FAM_DEC  ADD CONSTRAINT INF_FAM_DEC_UK_REF UNIQUE (INF_FAM_DEC__CODE);
ALTER TABLE INF.INF_GARE  ADD CONSTRAINT INF_GARE_UK_REF UNIQUE (INF_GARE__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_GARE__ID);
ALTER TABLE INF.INF_LIAISON  ADD CONSTRAINT INF_LIAISON_UK_REF UNIQUE (INF_LIAISON__CODE);
ALTER TABLE INF.INF_OCCUPATION  ADD CONSTRAINT INF_OCCUPATION_UK_REF UNIQUE (INF_OCCUPATION__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_OCCUPANT__ID,INF_CD_OCCUPATION__ID);
ALTER TABLE INF.INF_PAVE_VOIE  ADD CONSTRAINT INF_PAVE_VOIE_UK_REF UNIQUE (INF_PAVE_VOIE__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_VOIE__ID);
ALTER TABLE INF.INF_PK  ADD CONSTRAINT INF_PK_PK_UK_REF UNIQUE (INF_PK__ABS_CUM,INF_CHAUSSEE__ID);
ALTER TABLE INF.INF_PK  ADD CONSTRAINT INF_PK_PK_UK1 UNIQUE (INF_CHAUSSEE__ID,INF_PK__NUM);
ALTER TABLE INF.INF_PT_SING  ADD CONSTRAINT INF_PT_SING_UK_REF UNIQUE (INF_PT_SING__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_PT_SING__ID);
ALTER TABLE INF.INF_PRESTATAIRE  ADD CONSTRAINT INF_PRESTATAIRE_UK_REF UNIQUE (INF_PRESTATAIRE__CODE,INF_CD_PRESTATAIRE__ID);
ALTER TABLE INF.INF_REPARTITION_TRAFIC  ADD CONSTRAINT INF_REPARTITION_TRAFIC_UK_REF UNIQUE (INF_REPARTITION_TRAFIC__ANNEE,INF_REPARTITION_TRAFIC__ABS_DEB,INF_CHAUSSEE__ID);
ALTER TABLE INF.INF_REPERE  ADD CONSTRAINT INF_REPERE_UK_REF UNIQUE (INF_CHAUSSEE__ID,INF_REPERE__NUM);
ALTER TABLE INF.INF_SECTION_TRAFIC  ADD CONSTRAINT INF_SECTION_TRAFIC_UK_REF UNIQUE (INF_SECTION_TRAFIC__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_TRAFIC__ID);
ALTER TABLE INF.INF_SECURITE  ADD CONSTRAINT INF_SECURITE_UK_REF UNIQUE (INF_SECURITE__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_POSIT__ID,INF_CD_SECURITE__ID);
ALTER TABLE INF.INF_TALUS  ADD CONSTRAINT INF_TALUS_UK_REF UNIQUE (INF_TALUS__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_TALUS__ID);
ALTER TABLE INF.INF_TPC  ADD CONSTRAINT INF_TPC_UK_REF UNIQUE (INF_TPC__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_TPC__ID);
ALTER TABLE INF.INF_TR_DEC  ADD CONSTRAINT INF_TR_DEC_UK_REF UNIQUE (INF_TR_DEC__ABS_DEB,INF_CHAUSSEE__ID,INF_CD_DEC__ID);
ALTER TABLE INF.INF_CD_AIRE  ADD CONSTRAINT INF_CD_AIRE_UK_REF UNIQUE (INF_CD_AIRE__CODE);
ALTER TABLE INF.INF_CD_LIAISON  ADD CONSTRAINT INF_CD_LIAISON_UK_REF UNIQUE (INF_CD_LIAISON__CODE);
ALTER TABLE INF.INF_CD_PLACE  ADD CONSTRAINT INF_CD_PLACE_UK_REF UNIQUE (INF_CD_PLACE__CODE);
ALTER TABLE INF.INF_CD_PRESTATAIRE  ADD CONSTRAINT INF_CD_PRESTATAIRE_UK_REF UNIQUE (INF_CD_PRESTATAIRE__CODE);
ALTER TABLE INF.INF_CD_SERVICE  ADD CONSTRAINT INF_CD_SERVICE_UK_REF UNIQUE (INF_CD_SERVICE__CODE);
ALTER TABLE PRF.PRF_RIGHT  ADD CONSTRAINT PRF_RIGHT_UK_REF UNIQUE (PRF_RIGHT__CODE);
ALTER TABLE PRF.PRF_PROFIL  ADD CONSTRAINT PRF_PROFIL_UK_REF UNIQUE (PRF_PROFIL__CODE);
ALTER TABLE PRF.PRF_SCHEMA  ADD CONSTRAINT PRF_SCHEMA_UK_REF UNIQUE (PRF_SCHEMA__NAME);
ALTER TABLE PRF.PRF_TABLE  ADD CONSTRAINT PRF_TABLE_UK_REF UNIQUE (PRF_TABLE__NAME);
ALTER TABLE PRF.PRF_USER  ADD CONSTRAINT PRF_USER_UK_REF UNIQUE (PRF_USER__LOGIN);
ALTER TABLE PRF.PRF_USER  ADD CONSTRAINT PRF_USER_UK_2 UNIQUE (PRF_USER__NOM,PRF_USER__PRENOM);
ALTER TABLE SIG.SIG_TEMPLATE  ADD CONSTRAINT SIG_TEMPLATE__UK_REF UNIQUE (SIG_TEMPLATE__LIBELLE);
ALTER TABLE SIG.SIG_CD_LAYER  ADD CONSTRAINT SIG_CD_LAYER_UK_REF UNIQUE (SIG_CD_LAYER__CODE);
ALTER TABLE SIG.SIG_CD_NODE  ADD CONSTRAINT SIG_CD_NODE_UK_REF UNIQUE (SIG_CD_NODE__CODE);
ALTER TABLE SIG.SIG_CD_TEMPLATE  ADD CONSTRAINT SIG_CD_TEMPLATE_UK_REF UNIQUE (SIG_CD_TEMPLATE__CODE);

-- Clé étrangères
ALTER TABLE INF.INF_ACCIDENT ADD CONSTRAINT INF_CHAUSSEE__INF_ACCIDENT FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AIRE_PARKING ADD CONSTRAINT INF_AIRE__INF_AIRE_PARKING FOREIGN KEY (INF_AIRE__ID) 
REFERENCES INF.INF_AIRE (INF_AIRE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AIRE_PARKING ADD CONSTRAINT INF_CD_PARKING__INF_AIRE_PARKING FOREIGN KEY (INF_CD_PLACE__ID) 
REFERENCES INF.INF_CD_PLACE (INF_CD_PLACE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AIRE_PRESTATAIRE ADD CONSTRAINT INF_AIRE__INF_AIRE_PRESTATAIRE FOREIGN KEY (INF_AIRE__ID) 
REFERENCES INF.INF_AIRE (INF_AIRE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AIRE_PRESTATAIRE ADD CONSTRAINT INF_PRESTATAIRE__INF_AIRE_PRESTATAIRE FOREIGN KEY (INF_PRESTATAIRE__ID) 
REFERENCES INF.INF_PRESTATAIRE (INF_PRESTATAIRE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AIRE_SERVICE ADD CONSTRAINT INF_AIRE__INF_AIRE_SERVICE FOREIGN KEY (INF_AIRE__ID) 
REFERENCES INF.INF_AIRE (INF_AIRE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AIRE_SERVICE ADD CONSTRAINT INF_CD_SERVICE__INF_AIRE_SERVICE FOREIGN KEY (INF_CD_SERVICE__ID) 
REFERENCES INF.INF_CD_SERVICE (INF_CD_SERVICE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AIRE ADD CONSTRAINT INF_CHAUSSEE__INF_AIRE FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AIRE ADD CONSTRAINT INF_CD_AIRE__INF_AIRE FOREIGN KEY (INF_CD_AIRE__ID) 
REFERENCES INF.INF_CD_AIRE (INF_CD_AIRE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AMENAGEMENT ADD CONSTRAINT INF_CHAUSSEE__INF_AMENAGEMENT FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_AMENAGEMENT ADD CONSTRAINT INF_CD_AMENAGEMENT__INF_AMENAGEMENT FOREIGN KEY (INF_CD_AMENAGEMENT__ID) 
REFERENCES INF.INF_CD_AMENAGEMENT (INF_CD_AMENAGEMENT__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_PR_OLD ADD CONSTRAINT INF_CHAUSSEE__INF_PR_OLD FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_BIFURCATION ADD CONSTRAINT INF_CHAUSSEE__INF_BIFURCATION FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_BIFURCATION ADD CONSTRAINT INF_CD_BIFURCATION__INF_BIFURCATION FOREIGN KEY (INF_CD_BIFURCATION__ID) 
REFERENCES INF.INF_CD_BIFURCATION (INF_CD_BIFURCATION__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_BRETELLE ADD CONSTRAINT INF_CHAUSSEE__INF_BRETELLE FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_CHAUSSEE ADD CONSTRAINT INF_LIAISON__CHAUSSEE_INF FOREIGN KEY (INF_LIAISON__ID) 
REFERENCES INF.INF_LIAISON (INF_LIAISON__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_CLIMAT ADD CONSTRAINT INF_CHAUSSEE__INF_CLIMAT FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_CLIMAT ADD CONSTRAINT INF_CD_CLIMAT__INF_CLIMAT FOREIGN KEY (INF_CD_CLIMAT__ID) 
REFERENCES INF.INF_CD_CLIMAT (INF_CD_CLIMAT__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_CD_DEC ADD CONSTRAINT INF_FAM_DEC__INF_CD_DEC FOREIGN KEY (INF_FAM_DEC__ID) 
REFERENCES INF.INF_FAM_DEC (INF_FAM_DEC__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_CONTACT_CLS ADD CONSTRAINT INF_CLS__INF_CONTACT_CLS FOREIGN KEY (INF_CLS__ID) 
REFERENCES INF.INF_CLS (INF_CLS__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_CONTACT_CLS ADD CONSTRAINT INF_CONTACT__INF_CONTACT_CLS FOREIGN KEY (INF_CONTACT__ID) 
REFERENCES INF.INF_CONTACT (INF_CONTACT__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_DOC ADD CONSTRAINT INF_CD_DOC__INF_DOC FOREIGN KEY (INF_CD_DOC__ID) 
REFERENCES INF.INF_CD_DOC (INF_CD_DOC__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_DOC_CLS ADD CONSTRAINT ASSOCIATION_54 FOREIGN KEY (INF_DOC__ID) 
REFERENCES INF.INF_DOC (INF_DOC__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_DOC_CLS ADD CONSTRAINT INF_CLS__INF_DOC_CLS FOREIGN KEY (INF_CLS__ID) 
REFERENCES INF.INF_CLS (INF_CLS__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_ECLAIRAGE ADD CONSTRAINT INF_CHAUSSEE__INF_ECLAIRAGE FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_ECLAIRAGE ADD CONSTRAINT INF_CD_ECLAIRAGE__INF_ECLAIRAGE FOREIGN KEY (INF_CD_ECLAIRAGE__ID) 
REFERENCES INF.INF_CD_ECLAIRAGE (INF_CD_ECLAIRAGE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_ECLAIRAGE ADD CONSTRAINT INF_CD_POSIT__INF_ECLAIRAGE FOREIGN KEY (INF_CD_POSIT__ID) 
REFERENCES INF.INF_CD_POSIT (INF_CD_POSIT__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_GARE ADD CONSTRAINT INF_CHAUSSEE__INF_GARE FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_GARE ADD CONSTRAINT INF_CD_GARE__INF_GARE FOREIGN KEY (INF_CD_GARE__ID) 
REFERENCES INF.INF_CD_GARE (INF_CD_GARE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_LIAISON ADD CONSTRAINT INF_CD_LIAISON__INF_LIAISON FOREIGN KEY (INF_CD_LIAISON__ID) 
REFERENCES INF.INF_CD_LIAISON (INF_CD_LIAISON__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_OCCUPATION ADD CONSTRAINT INF_CHAUSSEE__INF_OCCUPATION FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_OCCUPATION ADD CONSTRAINT INF_CD_OCCUPANT__INF_OCCUPATION FOREIGN KEY (INF_CD_OCCUPANT__ID) 
REFERENCES INF.INF_CD_OCCUPANT (INF_CD_OCCUPANT__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_OCCUPATION ADD CONSTRAINT INF_CD_OCCUPATION__INF_OCCUPATION FOREIGN KEY (INF_CD_OCCUPATION__ID) 
REFERENCES INF.INF_CD_OCCUPATION (INF_CD_OCCUPATION__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_PAVE_VOIE ADD CONSTRAINT INF_CHAUSSEE__INF_PAVE_VOIE FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_PAVE_VOIE ADD CONSTRAINT INF_CD_VOIE__INF_PAVE_VOIE FOREIGN KEY (INF_CD_VOIE__ID) 
REFERENCES INF.INF_CD_VOIE (INF_CD_VOIE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_PK ADD CONSTRAINT INF_CHAUSSEE__INF_PK FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_PT_SING ADD CONSTRAINT INF_CHAUSSEE__INF_PT_SING FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_PT_SING ADD CONSTRAINT INF_CD_PT_SING__INF_PT_SING FOREIGN KEY (INF_CD_PT_SING__ID) 
REFERENCES INF.INF_CD_PT_SING (INF_CD_PT_SING__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_PRESTATAIRE ADD CONSTRAINT INF_CD_PRESTATAIRE__CD_PRESTATAIRE FOREIGN KEY (INF_CD_PRESTATAIRE__ID) 
REFERENCES INF.INF_CD_PRESTATAIRE (INF_CD_PRESTATAIRE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_REPARTITION_TRAFIC ADD CONSTRAINT INF_CHAUSSEE__INF_REPARTITION_TRAFIC FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_REPERE ADD CONSTRAINT INF_CHAUSSEE__INF_REPERE FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_SECTION_TRAFIC ADD CONSTRAINT INF_CHAUSSEE__INF_SECTION_TRAFIC FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_SECTION_TRAFIC ADD CONSTRAINT INF_CD_TRAFIC__INF_SECTION_TRAFIC FOREIGN KEY (INF_CD_TRAFIC__ID) 
REFERENCES INF.INF_CD_TRAFIC (INF_CD_TRAFIC__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_SECURITE ADD CONSTRAINT INF_CHAUSSEE__INF_SECURITE FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_SECURITE ADD CONSTRAINT INF_CD_POSIT__INF_SECURITE FOREIGN KEY (INF_CD_POSIT__ID) 
REFERENCES INF.INF_CD_POSIT (INF_CD_POSIT__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_SECURITE ADD CONSTRAINT INF_CD_SECURITE__INF_SECURITE FOREIGN KEY (INF_CD_SECURITE__ID) 
REFERENCES INF.INF_CD_SECURITE (INF_CD_SECURITE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_SENSIBLE ADD CONSTRAINT INF_CHAUSSEE__INF_SENSIBLE FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_SENSIBLE ADD CONSTRAINT INF_CD_SENSIBLE__INF_SENSIBLE FOREIGN KEY (INF_CD_SENSIBLE__ID) 
REFERENCES INF.INF_CD_SENSIBLE (INF_CD_SENSIBLE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_DASHBOARD ADD CONSTRAINT INF_CD_DASHBOARD__INF_DASHBOARD FOREIGN KEY (INF_CD_DASHBOARD__ID) 
REFERENCES INF.INF_CD_DASHBOARD (INF_CD_DASHBOARD__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_TALUS ADD CONSTRAINT INF_CHAUSSEE__INF_TALUS FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_TALUS ADD CONSTRAINT INF_CD_TALUS__INF_TALUS FOREIGN KEY (INF_CD_TALUS__ID) 
REFERENCES INF.INF_CD_TALUS (INF_CD_TALUS__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_TPC ADD CONSTRAINT INF_CHAUSSEE__INF_TPC FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_TPC ADD CONSTRAINT INF_CD_TPC__INF_TPC FOREIGN KEY (INF_CD_TPC__ID) 
REFERENCES INF.INF_CD_TPC (INF_CD_TPC__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_TR_DEC ADD CONSTRAINT INF_CHAUSSEE__INF_TR_DEC FOREIGN KEY (INF_CHAUSSEE__ID) 
REFERENCES INF.INF_CHAUSSEE (INF_CHAUSSEE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE INF.INF_TR_DEC ADD CONSTRAINT INF_CD_DEC__INF_TR_DEC FOREIGN KEY (INF_CD_DEC__ID) 
REFERENCES INF.INF_CD_DEC (INF_CD_DEC__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_PARAM ADD CONSTRAINT PRF_SCHEMA__PRF_PARAM FOREIGN KEY (PRF_SCHEMA__ID) 
REFERENCES PRF.PRF_SCHEMA (PRF_SCHEMA__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_PROFIL_RIGHT ADD CONSTRAINT PRF_RIGHT__PRF_PROFIL_RIGHT FOREIGN KEY (PRF_RIGHT__ID) 
REFERENCES PRF.PRF_RIGHT (PRF_RIGHT__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_PROFIL_RIGHT ADD CONSTRAINT PRF_PROFIL__PRF_PROFIL_RIGHT FOREIGN KEY (PRF_PROFIL__ID) 
REFERENCES PRF.PRF_PROFIL (PRF_PROFIL__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_RIGHT ADD CONSTRAINT PRF_SCHEMA__PRF_RIGHT FOREIGN KEY (PRF_SCHEMA__ID) 
REFERENCES PRF.PRF_SCHEMA (PRF_SCHEMA__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_USER_PROFIL ADD CONSTRAINT PRF_PROFIL__PRF_USER_PROFIL FOREIGN KEY (PRF_PROFIL__ID) 
REFERENCES PRF.PRF_PROFIL (PRF_PROFIL__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_USER_PROFIL ADD CONSTRAINT PRF_USER__PRF_USER_PROFIL FOREIGN KEY (PRF_USER__ID) 
REFERENCES PRF.PRF_USER (PRF_USER__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_PROFIL ADD CONSTRAINT ASSOCIATION_2 FOREIGN KEY (PRF_SCHEMA__ID) 
REFERENCES PRF.PRF_SCHEMA (PRF_SCHEMA__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_PROFIL_TABLE ADD CONSTRAINT PRF_PROFIL__PRF_PROFIL_TABLE FOREIGN KEY (PRF_PROFIL__ID) 
REFERENCES PRF.PRF_PROFIL (PRF_PROFIL__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_PROFIL_TABLE ADD CONSTRAINT PRF_TABLE__PRF_PROFIL_TABLE FOREIGN KEY (PRF_TABLE__ID) 
REFERENCES PRF.PRF_TABLE (PRF_TABLE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE PRF.PRF_TABLE ADD CONSTRAINT PRF_SCHEMA__PRF_TABLE FOREIGN KEY (PRF_SCHEMA__ID) 
REFERENCES PRF.PRF_SCHEMA (PRF_SCHEMA__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SIG.SIG_LAYER ADD CONSTRAINT SIG_CD_LAYER__SIG_LAYER FOREIGN KEY (SIG_CD_LAYER__ID) 
REFERENCES SIG.SIG_CD_LAYER (SIG_CD_LAYER__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SIG.SIG_NODE ADD CONSTRAINT SIG_CD_NODE__SIG_NODE FOREIGN KEY (SIG_CD_NODE__ID) 
REFERENCES SIG.SIG_CD_NODE (SIG_CD_NODE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SIG.SIG_NODE ADD CONSTRAINT SIG_TEMPLATE__SIG_NODE FOREIGN KEY (SIG_TEMPLATE__ID) 
REFERENCES SIG.SIG_TEMPLATE (SIG_TEMPLATE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SIG.SIG_NODE ADD CONSTRAINT SIG_NODE__SIG_LAYER FOREIGN KEY (SIG_LAYER__ID) 
REFERENCES SIG.SIG_LAYER (SIG_LAYER__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE SIG.SIG_TEMPLATE ADD CONSTRAINT SIG_CD_TEMPLATE__SIG_TEMPLATE FOREIGN KEY (SIG_CD_TEMPLATE__ID) 
REFERENCES SIG.SIG_CD_TEMPLATE (SIG_CD_TEMPLATE__ID) MATCH SIMPLE ON UPDATE CASCADE ON DELETE CASCADE;

-- Droit de l'utilisateur postgres
ALTER TABLE INF.INF_ACCIDENT OWNER TO postgres;
ALTER TABLE INF.INF_AIRE_PARKING OWNER TO postgres;
ALTER TABLE INF.INF_AIRE_PRESTATAIRE OWNER TO postgres;
ALTER TABLE INF.INF_AIRE_SERVICE OWNER TO postgres;
ALTER TABLE INF.INF_AIRE OWNER TO postgres;
ALTER TABLE INF.INF_AMENAGEMENT OWNER TO postgres;
ALTER TABLE INF.INF_PR_OLD OWNER TO postgres;
ALTER TABLE INF.INF_BIFURCATION OWNER TO postgres;
ALTER TABLE INF.INF_BRETELLE OWNER TO postgres;
ALTER TABLE INF.INF_CHAUSSEE OWNER TO postgres;
ALTER TABLE INF.INF_CD_TRAFIC OWNER TO postgres;
ALTER TABLE INF.INF_CLS OWNER TO postgres;
ALTER TABLE INF.INF_CLIMAT OWNER TO postgres;
ALTER TABLE INF.INF_CD_AMENAGEMENT OWNER TO postgres;
ALTER TABLE INF.INF_CD_BIFURCATION OWNER TO postgres;
ALTER TABLE INF.INF_CD_CLIMAT OWNER TO postgres;
ALTER TABLE INF.INF_CD_DEC OWNER TO postgres;
ALTER TABLE INF.INF_CD_DOC OWNER TO postgres;
ALTER TABLE INF.INF_CD_ECLAIRAGE OWNER TO postgres;
ALTER TABLE INF.INF_CD_GARE OWNER TO postgres;
ALTER TABLE INF.INF_CD_OCCUPANT OWNER TO postgres;
ALTER TABLE INF.INF_CD_OCCUPATION OWNER TO postgres;
ALTER TABLE INF.INF_CD_PT_SING OWNER TO postgres;
ALTER TABLE INF.INF_CD_POSIT OWNER TO postgres;
ALTER TABLE INF.INF_CD_SECURITE OWNER TO postgres;
ALTER TABLE INF.INF_CD_SENSIBLE OWNER TO postgres;
ALTER TABLE INF.INF_CD_DASHBOARD OWNER TO postgres;
ALTER TABLE INF.INF_CD_TALUS OWNER TO postgres;
ALTER TABLE INF.INF_CD_TPC OWNER TO postgres;
ALTER TABLE INF.INF_CD_VOIE OWNER TO postgres;
ALTER TABLE INF.INF_CONTACT_CLS OWNER TO postgres;
ALTER TABLE INF.INF_CONTACT OWNER TO postgres;
ALTER TABLE INF.INF_DOC OWNER TO postgres;
ALTER TABLE INF.INF_DOC_CLS OWNER TO postgres;
ALTER TABLE INF.INF_ECLAIRAGE OWNER TO postgres;
ALTER TABLE INF.INF_FAM_DEC OWNER TO postgres;
ALTER TABLE INF.INF_GARE OWNER TO postgres;
ALTER TABLE INF.INF_LIAISON OWNER TO postgres;
ALTER TABLE INF.INF_OCCUPATION OWNER TO postgres;
ALTER TABLE INF.INF_PAVE_VOIE OWNER TO postgres;
ALTER TABLE INF.INF_PK OWNER TO postgres;
ALTER TABLE INF.INF_PT_SING OWNER TO postgres;
ALTER TABLE INF.INF_PRESTATAIRE OWNER TO postgres;
ALTER TABLE INF.INF_REPARTITION_TRAFIC OWNER TO postgres;
ALTER TABLE INF.INF_REPERE OWNER TO postgres;
ALTER TABLE INF.INF_SECTION_TRAFIC OWNER TO postgres;
ALTER TABLE INF.INF_SECURITE OWNER TO postgres;
ALTER TABLE INF.INF_SENSIBLE OWNER TO postgres;
ALTER TABLE INF.INF_DASHBOARD OWNER TO postgres;
ALTER TABLE INF.INF_TALUS OWNER TO postgres;
ALTER TABLE INF.INF_TPC OWNER TO postgres;
ALTER TABLE INF.INF_TR_DEC OWNER TO postgres;
ALTER TABLE INF.INF_CD_AIRE OWNER TO postgres;
ALTER TABLE INF.INF_CD_LIAISON OWNER TO postgres;
ALTER TABLE INF.INF_CD_PLACE OWNER TO postgres;
ALTER TABLE INF.INF_CD_PRESTATAIRE OWNER TO postgres;
ALTER TABLE INF.INF_CD_SERVICE OWNER TO postgres;
ALTER TABLE PRF.PRF_LANG OWNER TO postgres;
ALTER TABLE PRF.PRF_PARAM OWNER TO postgres;
ALTER TABLE PRF.PRF_PROFIL_RIGHT OWNER TO postgres;
ALTER TABLE PRF.PRF_RIGHT OWNER TO postgres;
ALTER TABLE PRF.PRF_USER_PROFIL OWNER TO postgres;
ALTER TABLE PRF.PRF_PROFIL OWNER TO postgres;
ALTER TABLE PRF.PRF_SCHEMA OWNER TO postgres;
ALTER TABLE PRF.PRF_PROFIL_TABLE OWNER TO postgres;
ALTER TABLE PRF.PRF_TABLE OWNER TO postgres;
ALTER TABLE PRF.PRF_USER OWNER TO postgres;
ALTER TABLE SIG.SIG_LAYER OWNER TO postgres;
ALTER TABLE SIG.SIG_NODE OWNER TO postgres;
ALTER TABLE SIG.SIG_TEMPLATE OWNER TO postgres;
ALTER TABLE SIG.SIG_CD_LAYER OWNER TO postgres;
ALTER TABLE SIG.SIG_CD_NODE OWNER TO postgres;
ALTER TABLE SIG.SIG_CD_TEMPLATE OWNER TO postgres;

